/************************************************************************
 * dlb_adm
 * Copyright (c) 2021, Dolby Laboratories Inc.
 * Copyright (c) 2021, Dolby International AB.
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 **********************************************************************/

#ifndef DLB_ADM_COMMON_DEFINITIONS_H
#define DLB_ADM_COMMON_DEFINITIONS_H

// TODO: add HOA and Binaural common definitions (if needed)
// TODO: add audioStreamFormat and audioTrackFormat common definitions (if needed)

static const char admCommonDefinitionsXMLBuffer[] = 
"<?xml version=\'1.0\' encoding=\'utf-8\'?>\n"
"<ituADM xmlns=\"urn:metadata-schema:adm\">\n"
"  <coreMetadata>\n"
"    <format>\n"
"      <audioFormatExtended>\n"
"        <audioPackFormat audioPackFormatID=\"AP_00010001\" audioPackFormatName=\"urn:itu:bs:775:3:pack:mono_(0+1+0)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_00010002\" audioPackFormatName=\"urn:itu:bs:2051:0:pack:stereo_(0+2+0)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_0001000a\" audioPackFormatName=\"urn:itu:bs:775:3:pack:3.0_(0+3+0)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_0001000b\" audioPackFormatName=\"urn:itu:bs:775:3:pack:4.0_(0+4+0)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010009</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_0001000c\" audioPackFormatName=\"urn:itu:bs:2051:0:pack:5.0_(0+5+0)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010005</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010006</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_00010003\" audioPackFormatName=\"urn:itu:bs:2051:0:pack:5.1_(0+5+0)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010004</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010005</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010006</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_0001000d\" audioPackFormatName=\"6.1_(0+6+0)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010004</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010005</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010006</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010009</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_0001000e\" audioPackFormatName=\"7.1front_(0+7+0)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010004</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010005</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010006</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010026</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010027</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_0001000f\" audioPackFormatName=\"7.1back_(0+7+0)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010004</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000a</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000b</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001c</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001d</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_00010004\" audioPackFormatName=\"urn:itu:bs:2051:0:pack:7.1top_(2+5+0)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010004</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010005</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010006</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000d</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000f</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_00010012\" audioPackFormatName=\"7.1side_5.1+sc_(0+7+0)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010004</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010005</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010006</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010024</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010025</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_00010013\" audioPackFormatName=\"7.1topside_5.1.2_(2+5+0)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010004</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010005</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010006</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010013</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010014</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_00010014\" audioPackFormatName=\"9.1screen_5.1.2+sc_(2+7+0)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010004</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010005</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010006</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010013</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010014</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010024</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010025</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_00010016\" audioPackFormatName=\"9.1_7.1.2_(2+7+0)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010004</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000b</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000c</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001c</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001d</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010013</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010014</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_00010005\" audioPackFormatName=\"urn:itu:bs:2051:0:pack:9.1_5.1.4_(4+5+0)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010004</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010005</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010006</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000d</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000f</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010010</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010012</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_00010010\" audioPackFormatName=\"urn:itu:bs:2051:0:pack:10.1_(4+5+1)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010004</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010005</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010006</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000d</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000f</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010010</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010012</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010015</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_00010007\" audioPackFormatName=\"urn:itu:bs:2051:0:pack:10.2_(3+7+0)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010022</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010023</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000a</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000b</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001c</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001d</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010028</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010020</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010021</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_00010015\" audioPackFormatName=\"11.1_5.1.4+sc_(4+7+0)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010004</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010005</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010006</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000d</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000f</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010010</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010012</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010024</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010025</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_00010017\" audioPackFormatName=\"11.1_7.1.4_(4+7+0)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010004</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000a</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000b</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001c</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001d</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010022</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010023</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001e</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001f</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_00010008\" audioPackFormatName=\"urn:itu:bs:2051:0:pack:13.1_(4+9+0)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010004</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000a</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000b</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001c</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001d</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010022</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010023</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001e</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001f</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010024</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010025</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_00010009\" audioPackFormatName=\"urn:itu:bs:2051:0:pack:22.2_(9+10+3)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010018</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010019</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010020</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001c</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001d</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010009</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010021</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000a</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000b</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010022</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010023</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000e</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000c</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001e</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001f</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010013</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010014</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010011</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010015</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010016</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010017</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioPackFormat audioPackFormatID=\"AP_00010011\" audioPackFormatName=\"Auro-3D_(9+9+0)\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioChannelFormatIDRef>AC_00010001</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010002</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010003</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010004</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010005</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010006</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000a</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000b</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001a</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001b</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000d</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000f</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001000e</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010010</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010012</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010013</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_00010014</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001e</audioChannelFormatIDRef>\n"
"          <audioChannelFormatIDRef>AC_0001001f</audioChannelFormatIDRef>\n"
"        </audioPackFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010001\" audioChannelFormatName=\"FrontLeft\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010001_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:M+030</speakerLabel>\n"
"            <position coordinate=\"azimuth\">30.0</position>\n"
"            <position coordinate=\"elevation\">0.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010002\" audioChannelFormatName=\"FrontRight\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010002_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:M-030</speakerLabel>\n"
"            <position coordinate=\"azimuth\">-30.0</position>\n"
"            <position coordinate=\"elevation\">0.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010003\" audioChannelFormatName=\"FrontCentre\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010003_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:M+000</speakerLabel>\n"
"            <position coordinate=\"azimuth\">0.0</position>\n"
"            <position coordinate=\"elevation\">0.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010004\" audioChannelFormatName=\"LowFrequencyEffects\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <frequency typeDefinition=\"lowPass\">120.0</frequency>\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010004_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:LFE</speakerLabel>\n"
"            <position coordinate=\"azimuth\">0.0</position>\n"
"            <position coordinate=\"elevation\">-30.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010005\" audioChannelFormatName=\"SurroundLeft\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010005_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:M+110</speakerLabel>\n"
"            <position coordinate=\"azimuth\">110.0</position>\n"
"            <position coordinate=\"elevation\">0.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010006\" audioChannelFormatName=\"SurroundRight\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010006_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:M-110</speakerLabel>\n"
"            <position coordinate=\"azimuth\">-110.0</position>\n"
"            <position coordinate=\"elevation\">0.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010007\" audioChannelFormatName=\"FrontLeftOfCentre\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010007_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:M+022</speakerLabel>\n"
"            <position coordinate=\"azimuth\">22.5</position>\n"
"            <position coordinate=\"elevation\">0.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010008\" audioChannelFormatName=\"FrontRightOfCentre\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010008_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:M-022</speakerLabel>\n"
"            <position coordinate=\"azimuth\">-22.5</position>\n"
"            <position coordinate=\"elevation\">0.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010009\" audioChannelFormatName=\"BackCentre\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010009_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:M+180</speakerLabel>\n"
"            <position coordinate=\"azimuth\">180.0</position>\n"
"            <position coordinate=\"elevation\">0.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_0001000a\" audioChannelFormatName=\"SideLeft\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_0001000a_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:M+090</speakerLabel>\n"
"            <position coordinate=\"azimuth\">90.0</position>\n"
"            <position coordinate=\"elevation\">0.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_0001000b\" audioChannelFormatName=\"SideRight\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_0001000b_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:M-090</speakerLabel>\n"
"            <position coordinate=\"azimuth\">-90.0</position>\n"
"            <position coordinate=\"elevation\">0.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_0001000c\" audioChannelFormatName=\"TopCentre\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_0001000c_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:T+000</speakerLabel>\n"
"            <position coordinate=\"azimuth\">0.0</position>\n"
"            <position coordinate=\"elevation\">90.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_0001000d\" audioChannelFormatName=\"TopFrontLeft\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_0001000d_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:U+030</speakerLabel>\n"
"            <position coordinate=\"azimuth\">30.0</position>\n"
"            <position coordinate=\"elevation\">30.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_0001000e\" audioChannelFormatName=\"TopFrontCentre\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_0001000e_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:U+000</speakerLabel>\n"
"            <position coordinate=\"azimuth\">0.0</position>\n"
"            <position coordinate=\"elevation\">30.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_0001000f\" audioChannelFormatName=\"TopFrontRight\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_0001000f_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:U-030</speakerLabel>\n"
"            <position coordinate=\"azimuth\">-30.0</position>\n"
"            <position coordinate=\"elevation\">30.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010010\" audioChannelFormatName=\"TopSurroundLeft\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010010_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:U+110</speakerLabel>\n"
"            <position coordinate=\"azimuth\">110.0</position>\n"
"            <position coordinate=\"elevation\">30.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010011\" audioChannelFormatName=\"TopBackCentre\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010011_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:U+180</speakerLabel>\n"
"            <position coordinate=\"azimuth\">180.0</position>\n"
"            <position coordinate=\"elevation\">30.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010012\" audioChannelFormatName=\"TopSurroundRight\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010012_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:U-110</speakerLabel>\n"
"            <position coordinate=\"azimuth\">-110.0</position>\n"
"            <position coordinate=\"elevation\">30.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010013\" audioChannelFormatName=\"TopSideLeft\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010013_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:U+090</speakerLabel>\n"
"            <position coordinate=\"azimuth\">90.0</position>\n"
"            <position coordinate=\"elevation\">30.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010014\" audioChannelFormatName=\"TopSideRight\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010014_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:U-090</speakerLabel>\n"
"            <position coordinate=\"azimuth\">-90.0</position>\n"
"            <position coordinate=\"elevation\">30.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010015\" audioChannelFormatName=\"BottomFrontCentre\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010015_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:B+000</speakerLabel>\n"
"            <position coordinate=\"azimuth\">0.0</position>\n"
"            <position coordinate=\"elevation\">-30.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010016\" audioChannelFormatName=\"BottomFrontLeftMid\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010016_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:B+045</speakerLabel>\n"
"            <position coordinate=\"azimuth\">45.0</position>\n"
"            <position coordinate=\"elevation\">-30.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010017\" audioChannelFormatName=\"BottomFrontRightMid\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010017_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:B-045</speakerLabel>\n"
"            <position coordinate=\"azimuth\">-45.0</position>\n"
"            <position coordinate=\"elevation\">-30.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010018\" audioChannelFormatName=\"FrontLeftWide\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010018_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:M+060</speakerLabel>\n"
"            <position coordinate=\"azimuth\">60.0</position>\n"
"            <position coordinate=\"elevation\">0.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010019\" audioChannelFormatName=\"FrontRightWide\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010019_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:M-060</speakerLabel>\n"
"            <position coordinate=\"azimuth\">-60.0</position>\n"
"            <position coordinate=\"elevation\">0.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_0001001a\" audioChannelFormatName=\"BackLeftMidDiffuse\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_0001001a_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:M+135_Diff</speakerLabel>\n"
"            <position coordinate=\"azimuth\">135.0</position>\n"
"            <position coordinate=\"elevation\">0.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_0001001b\" audioChannelFormatName=\"BackRightMidDiffuse\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_0001001b_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:M-135_Diff</speakerLabel>\n"
"            <position coordinate=\"azimuth\">-135.0</position>\n"
"            <position coordinate=\"elevation\">0.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_0001001c\" audioChannelFormatName=\"BackLeftMid\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_0001001c_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:M+135</speakerLabel>\n"
"            <position coordinate=\"azimuth\">135.0</position>\n"
"            <position coordinate=\"elevation\">0.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_0001001d\" audioChannelFormatName=\"BackRightMid\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_0001001d_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:M-135</speakerLabel>\n"
"            <position coordinate=\"azimuth\">-135.0</position>\n"
"            <position coordinate=\"elevation\">0.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_0001001e\" audioChannelFormatName=\"TopBackLeftMid\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_0001001e_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:U+135</speakerLabel>\n"
"            <position coordinate=\"azimuth\">135.0</position>\n"
"            <position coordinate=\"elevation\">30.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_0001001f\" audioChannelFormatName=\"TopBackRightMid\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_0001001f_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:U-135</speakerLabel>\n"
"            <position coordinate=\"azimuth\">-135.0</position>\n"
"            <position coordinate=\"elevation\">30.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010020\" audioChannelFormatName=\"LowFrequencyEffectsL\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <frequency typeDefinition=\"lowPass\">120.0</frequency>\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010020_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:LFEL</speakerLabel>\n"
"            <position coordinate=\"azimuth\">45.0</position>\n"
"            <position coordinate=\"elevation\">-30.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010021\" audioChannelFormatName=\"LowFrequencyEffectsR\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <frequency typeDefinition=\"lowPass\">120.0</frequency>\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010021_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:LFER</speakerLabel>\n"
"            <position coordinate=\"azimuth\">-45.0</position>\n"
"            <position coordinate=\"elevation\">-30.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010022\" audioChannelFormatName=\"TopFrontLeftMid\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010022_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:U+045</speakerLabel>\n"
"            <position coordinate=\"azimuth\">45.0</position>\n"
"            <position coordinate=\"elevation\">30.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010023\" audioChannelFormatName=\"TopFrontRightMid\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010023_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:U-045</speakerLabel>\n"
"            <position coordinate=\"azimuth\">-45.0</position>\n"
"            <position coordinate=\"elevation\">30.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010024\" audioChannelFormatName=\"FrontLeftScreen\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010024_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:M+SC</speakerLabel>\n"
"            <position coordinate=\"azimuth\" screenEdgeLock=\"left\">25.0</position>\n"
"            <position coordinate=\"elevation\">0.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010025\" audioChannelFormatName=\"FrontRightScreen\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010025_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:M-SC</speakerLabel>\n"
"            <position coordinate=\"azimuth\" screenEdgeLock=\"right\">-25.0</position>\n"
"            <position coordinate=\"elevation\">0.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010026\" audioChannelFormatName=\"FrontLeftMid\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010026_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:M+045</speakerLabel>\n"
"            <position coordinate=\"azimuth\">45.0</position>\n"
"            <position coordinate=\"elevation\">0.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010027\" audioChannelFormatName=\"FrontRightMid\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010027_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:M-045</speakerLabel>\n"
"            <position coordinate=\"azimuth\">-45.0</position>\n"
"            <position coordinate=\"elevation\">0.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"        <audioChannelFormat audioChannelFormatID=\"AC_00010028\" audioChannelFormatName=\"UpperTopBackCentre\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"          <audioBlockFormat audioBlockFormatID=\"AB_00010028_00000001\">\n"
"            <speakerLabel>urn:itu:bs:2051:0:speaker:UH+180</speakerLabel>\n"
"            <position coordinate=\"azimuth\">180.0</position>\n"
"            <position coordinate=\"elevation\">45.0</position>\n"
"            <position coordinate=\"distance\">1.0</position>\n"
"          </audioBlockFormat>\n"
"        </audioChannelFormat>\n"
"      </audioFormatExtended>\n"
"    </format>\n"
"  </coreMetadata>\n"
"</ituADM>\n"
;

#endif // DLB_ADM_COMMON_DEFINITIONS_H
