/******************************************************************************
 * This program is protected under international and U.S. copyright laws as
 * an unpublished work. This program is confidential and proprietary to the
 * copyright owners. Reproduction or disclosure, in whole or in part, or the
 * production of derivative works therefrom without the express permission of
 * the copyright owners is prohibited.
 *
 *                Copyright (C) 2020-2021 by Dolby Laboratories,
 *                Copyright (C) 2020-2021 by Dolby International AB.
 *                            All rights reserved.
 ******************************************************************************/

#ifndef DLB_ADM_UNIT_TEST_DATA_H
#define DLB_ADM_UNIT_TEST_DATA_H

static const char stereoXML[] GTEST_ATTRIBUTE_UNUSED_ =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<frame>\n"
"  <frameHeader>\n"
"    <frameFormat frameFormatID=\"FF_00000000001\" type=\"full\" start=\"00:00:00.00000\" duration=\"00:00:00.02000\" flowID=\"f8cc7821-09b2-41cb-bd42-ec35e9fcb9a8\">\n"
"    </frameFormat>\n"
"    <transportTrackFormat transportID=\"TP_0001\" transportName=\"X\" numIDs=\"4\" numTracks=\"4\">\n"
"      <audioTrack trackID=\"1\">\n"
"        <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"2\">\n"
"        <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"3\">\n"
"        <audioTrackUIDRef>ATU_00000003</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"4\">\n"
"        <audioTrackUIDRef>ATU_00000004</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"    </transportTrackFormat>\n"
"  </frameHeader>\n"
"  <audioFormatExtended version=\"ITU-R_BS.2076-2\">\n"
"    <audioProgramme audioProgrammeID=\"APR_1001\" audioProgrammeName=\"English\" audioProgrammeLanguage=\"en\">\n"
"      <audioProgrammeLabel language=\"en\">English</audioProgrammeLabel>\n"
"      <audioContentIDRef>ACO_1001</audioContentIDRef>\n"
"      <audioContentIDRef>ACO_1002</audioContentIDRef>\n"
"    </audioProgramme>\n"
"    <audioProgramme audioProgrammeID=\"APR_1002\" audioProgrammeName=\"Francais\" audioProgrammeLanguage=\"fr\">\n"
"      <audioProgrammeLabel language=\"fr\">Francais</audioProgrammeLabel>\n"
"      <audioContentIDRef>ACO_1001</audioContentIDRef>\n"
"      <audioContentIDRef>ACO_1003</audioContentIDRef>\n"
"    </audioProgramme>\n"
"    <audioContent audioContentID=\"ACO_1001\" audioContentName=\"Main Stereo Bed\">\n"
"      <audioContentLabel language=\"en\">Main Stereo Bed</audioContentLabel>\n"
"      <dialogue mixedContentKind=\"2\">2</dialogue>\n"
"      <audioObjectIDRef>AO_1001</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioContent audioContentID=\"ACO_1002\" audioContentName=\"English Dialog\">\n"
"      <audioContentLabel language=\"en\">English Dialog</audioContentLabel>\n"
"      <dialogue dialogueContentKind=\"1\">1</dialogue>\n"
"      <audioObjectIDRef>AO_1002</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioContent audioContentID=\"ACO_1003\" audioContentName=\"Dialogue Francaise\">\n"
"      <audioContentLabel language=\"fr\">Dialogue Francaise</audioContentLabel>\n"
"      <dialogue dialogueContentKind=\"1\">1</dialogue>\n"
"      <audioObjectIDRef>AO_1003</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioObject audioObjectID=\"AO_1001\" audioObjectName=\"Main Stereo Bed\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioObject audioObjectID=\"AO_1002\" audioObjectName=\"English Dialog\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00031002</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000003</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioObject audioObjectID=\"AO_1003\" audioObjectName=\"Dialogue Francaise\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00031003</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000004</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00011001\" audioPackFormatName=\"RoomCentric_2.0\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00031002\" audioPackFormatName=\"English Dialog\" typeLabel=\"0003\" typeDefinition=\"Objects\">\n"
"      <audioChannelFormatIDRef>AC_00031002</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00031003\" audioPackFormatName=\"Dialogue Francaise\" typeLabel=\"0003\" typeDefinition=\"Objects\">\n"
"      <audioChannelFormatIDRef>AC_00031003</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011001\" audioChannelFormatName=\"RoomCentricLeft\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011001_00000001\">\n"
"        <speakerLabel>RC_L</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011002\" audioChannelFormatName=\"RoomCentricRight\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011002_00000001\">\n"
"        <speakerLabel>RC_R</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00031002\" audioChannelFormatName=\"English Dialog\" typeLabel=\"0003\" typeDefinition=\"Objects\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00031002_00000001\">\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">0.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00031003\" audioChannelFormatName=\"Dialogue Francaise\" typeLabel=\"0003\" typeDefinition=\"Objects\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00031003_00000001\">\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">0.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioTrackUID UID=\"ATU_00000001\">\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000002\">\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000003\">\n"
"      <audioPackFormatIDRef>AP_00031002</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00031002</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000004\">\n"
"      <audioPackFormatIDRef>AP_00031003</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00031003</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"  </audioFormatExtended>\n"
"</frame>\n"
;

static const char dolbyReferenceXML[] GTEST_ATTRIBUTE_UNUSED_ =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
"<frame>\n"
"  <frameHeader>\n"
"    <frameFormat frameFormatID=\"FF_00000000001\" type=\"full\" start=\"00:00:00.00000\" duration=\"00:00:00.02000\" flowID=\"f8cc7821-09b2-41cb-bd42-ec35e9fcb9a8\">\n"
"      <changedIDs>\n"
"        <audioProgrammeIDRef>APR_1001</audioProgrammeIDRef>\n"
"        <audioProgrammeIDRef>APR_1002</audioProgrammeIDRef>\n"
"        <audioProgrammeIDRef>APR_1003</audioProgrammeIDRef>\n"
"        <audioContentIDRef>ACO_1001</audioContentIDRef>\n"
"        <audioContentIDRef>ACO_1003</audioContentIDRef>\n"
"        <audioContentIDRef>ACO_1004</audioContentIDRef>\n"
"        <audioContentIDRef>ACO_1005</audioContentIDRef>\n"
"        <audioObjectIDRef>AO_1001</audioObjectIDRef>\n"
"        <audioObjectIDRef>AO_1003</audioObjectIDRef>\n"
"        <audioObjectIDRef>AO_1004</audioObjectIDRef>\n"
"        <audioObjectIDRef>AO_1005</audioObjectIDRef>\n"
"        <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"        <audioPackFormatIDRef>AP_00031001</audioPackFormatIDRef>\n"
"        <audioPackFormatIDRef>AP_00031002</audioPackFormatIDRef>\n"
"        <audioPackFormatIDRef>AP_00031003</audioPackFormatIDRef>\n"
"        <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"        <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"        <audioChannelFormatIDRef>AC_00011003</audioChannelFormatIDRef>\n"
"        <audioChannelFormatIDRef>AC_00011004</audioChannelFormatIDRef>\n"
"        <audioChannelFormatIDRef>AC_00011005</audioChannelFormatIDRef>\n"
"        <audioChannelFormatIDRef>AC_00011006</audioChannelFormatIDRef>\n"
"        <audioChannelFormatIDRef>AC_00031001</audioChannelFormatIDRef>\n"
"        <audioChannelFormatIDRef>AC_00031002</audioChannelFormatIDRef>\n"
"        <audioChannelFormatIDRef>AC_00031003</audioChannelFormatIDRef>\n"
"        <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"        <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"        <audioTrackUIDRef>ATU_00000003</audioTrackUIDRef>\n"
"        <audioTrackUIDRef>ATU_00000004</audioTrackUIDRef>\n"
"        <audioTrackUIDRef>ATU_00000005</audioTrackUIDRef>\n"
"        <audioTrackUIDRef>ATU_00000006</audioTrackUIDRef>\n"
"        <audioTrackUIDRef>ATU_00000007</audioTrackUIDRef>\n"
"        <audioTrackUIDRef>ATU_00000008</audioTrackUIDRef>\n"
"        <audioTrackUIDRef>ATU_00000009</audioTrackUIDRef>\n"
"      </changedIDs>\n"
"    </frameFormat>\n"
"    <transportTrackFormat transportID=\"TP_0001\" transportName=\"X\" numIDs=\"9\" numTracks=\"9\">\n"
"      <audioTrack trackID=\"1\">\n"
"        <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"2\">\n"
"        <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"3\">\n"
"        <audioTrackUIDRef>ATU_00000003</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"4\">\n"
"        <audioTrackUIDRef>ATU_00000004</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"5\">\n"
"        <audioTrackUIDRef>ATU_00000005</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"6\">\n"
"        <audioTrackUIDRef>ATU_00000006</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"7\">\n"
"        <audioTrackUIDRef>ATU_00000007</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"8\">\n"
"        <audioTrackUIDRef>ATU_00000008</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"9\">\n"
"        <audioTrackUIDRef>ATU_00000009</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"    </transportTrackFormat>\n"
"  </frameHeader>\n"
"  <audioFormatExtended version=\"ITU-R_BS.2076-2\">\n"
"    <audioProgramme audioProgrammeID=\"APR_1001\" audioProgrammeName=\"English\" audioProgrammeLanguage=\"eng\">\n"
"      <audioProgrammeLabel language=\"eng\">English</audioProgrammeLabel>\n"
"      <audioContentIDRef>ACO_1001</audioContentIDRef>\n"
"      <audioContentIDRef>ACO_1003</audioContentIDRef>\n"
"    </audioProgramme>\n"
"    <audioProgramme audioProgrammeID=\"APR_1002\" audioProgrammeName=\"Spanish\" audioProgrammeLanguage=\"spa\">\n"
"      <audioProgrammeLabel language=\"eng\">Spanish</audioProgrammeLabel>\n"
"      <audioProgrammeLabel language=\"spa\">Espanol</audioProgrammeLabel>\n"
"      <audioContentIDRef>ACO_1001</audioContentIDRef>\n"
"      <audioContentIDRef>ACO_1004</audioContentIDRef>\n"
"    </audioProgramme>\n"
"    <audioProgramme audioProgrammeID=\"APR_1003\" audioProgrammeName=\"Chinese\" audioProgrammeLanguage=\"und\">\n"
"      <audioProgrammeLabel language=\"eng\">Chinese</audioProgrammeLabel>\n"
"      <audioContentIDRef>ACO_1001</audioContentIDRef>\n"
"      <audioContentIDRef>ACO_1005</audioContentIDRef>\n"
"    </audioProgramme>\n"
"    <audioContent audioContentID=\"ACO_1001\" audioContentName=\"Master Audio bed\">\n"
"      <dialogue mixedContentKind=\"2\">2</dialogue>\n"
"      <audioObjectIDRef>AO_1001</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioContent audioContentID=\"ACO_1003\" audioContentName=\"English\">\n"
"      <dialogue dialogueContentKind=\"1\">1</dialogue>\n"
"      <audioObjectIDRef>AO_1003</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioContent audioContentID=\"ACO_1004\" audioContentName=\"Spanish\">\n"
"      <dialogue dialogueContentKind=\"1\">1</dialogue>\n"
"      <audioObjectIDRef>AO_1004</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioContent audioContentID=\"ACO_1005\" audioContentName=\"Chinese\">\n"
"      <dialogue dialogueContentKind=\"1\">1</dialogue>\n"
"      <audioObjectIDRef>AO_1005</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioObject audioObjectID=\"AO_1001\" audioObjectName=\"Primary\">\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000003</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000004</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000005</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000006</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioObject audioObjectID=\"AO_1003\" audioObjectName=\"English\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00031001</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000007</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioObject audioObjectID=\"AO_1004\" audioObjectName=\"Spanish\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00031002</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000008</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioObject audioObjectID=\"AO_1005\" audioObjectName=\"Chinese\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00031003</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000009</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00011001\" audioPackFormatName=\"Primary\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011003</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011004</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011005</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011006</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00031001\" audioPackFormatName=\"English\" typeLabel=\"0003\" typeDefinition=\"Objects\">\n"
"      <audioChannelFormatIDRef>AC_00031001</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00031002\" audioPackFormatName=\"Spanish\" typeLabel=\"0003\" typeDefinition=\"Objects\">\n"
"      <audioChannelFormatIDRef>AC_00031002</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00031003\" audioPackFormatName=\"Chinese\" typeLabel=\"0003\" typeDefinition=\"Objects\">\n"
"      <audioChannelFormatIDRef>AC_00031003</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011001\" audioChannelFormatName=\"RoomCentricLeft\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011001_00000001\">\n"
"        <speakerLabel>RC_L</speakerLabel>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011002\" audioChannelFormatName=\"RoomCentricRight\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011002_00000001\">\n"
"        <speakerLabel>RC_R</speakerLabel>\n"
"        <position coordinate=\"X\">1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011003\" audioChannelFormatName=\"RoomCentricCenter\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011003_00000001\">\n"
"        <speakerLabel>RC_C</speakerLabel>\n"
"        <position coordinate=\"X\">0.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011004\" audioChannelFormatName=\"RoomCentricLFE\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011004_00000001\">\n"
"        <speakerLabel>RC_LFE</speakerLabel>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">-1.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011005\" audioChannelFormatName=\"RoomCentricLeftSideSurround\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011005_00000001\">\n"
"        <speakerLabel>RC_Lss</speakerLabel>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">0.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011006\" audioChannelFormatName=\"RoomCentricRightSideSurround\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011006_00000001\">\n"
"        <speakerLabel>RC_Rss</speakerLabel>\n"
"        <position coordinate=\"X\">1.00</position>\n"
"        <position coordinate=\"Y\">0.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00031001\" audioChannelFormatName=\"English\" typeLabel=\"0003\" typeDefinition=\"Objects\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00031001_00000001\">\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">0.00</position>\n"
"        <position coordinate=\"Y\">0.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00031002\" audioChannelFormatName=\"Spanish\" typeLabel=\"0003\" typeDefinition=\"Objects\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00031002_00000001\">\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">0.00</position>\n"
"        <position coordinate=\"Y\">0.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00031003\" audioChannelFormatName=\"Chinese\" typeLabel=\"0003\" typeDefinition=\"Objects\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00031003_00000001\">\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">0.00</position>\n"
"        <position coordinate=\"Y\">0.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioTrackUID UID=\"ATU_00000001\">\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000002\">\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000003\">\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011003</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000004\">\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011004</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000005\">\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011005</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000006\">\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011006</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000007\">\n"
"      <audioPackFormatIDRef>AP_00031001</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00031001</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000008\">\n"
"      <audioPackFormatIDRef>AP_00031002</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00031002</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000009\">\n"
"      <audioPackFormatIDRef>AP_00031003</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00031003</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"  </audioFormatExtended>\n"
"</frame>\n"
;

static const char ebuPart1XML[] GTEST_ATTRIBUTE_UNUSED_ =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<frame>\n"
"  <frameHeader>\n"
"    <frameFormat frameFormatID=\"FF_00000000001\" type=\"full\" start=\"00:00:00.00000\" duration=\"00:00:00.02000\" timeReference=\"local\" flowID=\"af419c78-9712-4e9d-a6d8-e44546e31fe6\">\n"
"      <changedIDs>\n"
"        <audioProgrammeIDRef>APR_1001</audioProgrammeIDRef>\n"
"        <audioProgrammeIDRef>APR_1002</audioProgrammeIDRef>\n"
"        <audioProgrammeIDRef>APR_1003</audioProgrammeIDRef>\n"
"        <audioProgrammeIDRef>APR_1004</audioProgrammeIDRef>\n"
"        <audioProgrammeIDRef>APR_1005</audioProgrammeIDRef>\n"
"        <audioContentIDRef>ACO_1001</audioContentIDRef>\n"
"        <audioContentIDRef>ACO_1002</audioContentIDRef>\n"
"        <audioContentIDRef>ACO_1003</audioContentIDRef>\n"
"        <audioContentIDRef>ACO_1004</audioContentIDRef>\n"
"        <audioContentIDRef>ACO_1005</audioContentIDRef>\n"
"        <audioContentIDRef>ACO_1006</audioContentIDRef>\n"
"        <audioObjectIDRef>AO_1001</audioObjectIDRef>\n"
"        <audioObjectIDRef>AO_1002</audioObjectIDRef>\n"
"        <audioObjectIDRef>AO_1003</audioObjectIDRef>\n"
"        <audioObjectIDRef>AO_1004</audioObjectIDRef>\n"
"        <audioObjectIDRef>AO_1005</audioObjectIDRef>\n"
"        <audioObjectIDRef>AO_1006</audioObjectIDRef>\n"
"        <audioPackFormatIDRef>AP_00010001</audioPackFormatIDRef>\n"
"        <audioPackFormatIDRef>AP_00010005</audioPackFormatIDRef>\n"
"        <audioTrackFormatIDRef>AT_00010001_01</audioTrackFormatIDRef>\n"
"        <audioTrackFormatIDRef>AT_00010002_01</audioTrackFormatIDRef>\n"
"        <audioTrackFormatIDRef>AT_00010003_01</audioTrackFormatIDRef>\n"
"        <audioTrackFormatIDRef>AT_00010004_01</audioTrackFormatIDRef>\n"
"        <audioTrackFormatIDRef>AT_00010005_01</audioTrackFormatIDRef>\n"
"        <audioTrackFormatIDRef>AT_00010006_01</audioTrackFormatIDRef>\n"
"        <audioTrackFormatIDRef>AT_0001000D_01</audioTrackFormatIDRef>\n"
"        <audioTrackFormatIDRef>AT_0001000F_01</audioTrackFormatIDRef>\n"
"        <audioTrackFormatIDRef>AT_00010010_01</audioTrackFormatIDRef>\n"
"        <audioTrackFormatIDRef>AT_00010012_01</audioTrackFormatIDRef>\n"
"      </changedIDs>\n"
"    </frameFormat>\n"
"    <transportTrackFormat transportID=\"TP_0001\" transportName=\"X\" numIDs=\"15\" numTracks=\"15\">\n"
"      <audioTrack trackID=\"1\">\n"
"        <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"2\">\n"
"        <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"3\">\n"
"        <audioTrackUIDRef>ATU_00000003</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"4\">\n"
"        <audioTrackUIDRef>ATU_00000004</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"5\">\n"
"        <audioTrackUIDRef>ATU_00000005</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"6\">\n"
"        <audioTrackUIDRef>ATU_00000006</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"7\">\n"
"        <audioTrackUIDRef>ATU_00000007</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"8\">\n"
"        <audioTrackUIDRef>ATU_00000008</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"9\">\n"
"        <audioTrackUIDRef>ATU_00000009</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"10\">\n"
"        <audioTrackUIDRef>ATU_0000000A</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"11\">\n"
"        <audioTrackUIDRef>ATU_0000000B</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"12\">\n"
"        <audioTrackUIDRef>ATU_0000000C</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"13\">\n"
"        <audioTrackUIDRef>ATU_0000000D</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"14\">\n"
"        <audioTrackUIDRef>ATU_0000000E</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"15\">\n"
"        <audioTrackUIDRef>ATU_0000000F</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"    </transportTrackFormat>\n"
"  </frameHeader>\n"
"  <audioFormatExtended version=\"ITU-R_BS.2076-2\">\n"
"    <audioProgramme audioProgrammeID=\"APR_1001\" audioProgrammeName=\"ESC Netherlands English\" audioProgrammeLanguage=\"eng\">\n"
"      <audioProgrammeLabel language=\"fre\">ESC Les Pays-Bas Anglais</audioProgrammeLabel>\n"
"      <audioProgrammeLabel language=\"eng\">ESC Netherlands English</audioProgrammeLabel>\n"
"      <audioContentIDRef>ACO_1001</audioContentIDRef>\n"
"      <audioContentIDRef>ACO_1002</audioContentIDRef>\n"
"    </audioProgramme>\n"
"    <audioProgramme audioProgrammeID=\"APR_1002\" audioProgrammeName=\"ESC Netherlands French\" audioProgrammeLanguage=\"fre\">\n"
"      <audioProgrammeLabel language=\"fre\">ESC Les Pays-Bas Francais</audioProgrammeLabel>\n"
"      <audioProgrammeLabel language=\"eng\">ESC Netherlands French</audioProgrammeLabel>\n"
"      <audioContentIDRef>ACO_1001</audioContentIDRef>\n"
"      <audioContentIDRef>ACO_1003</audioContentIDRef>\n"
"    </audioProgramme>\n"
"    <audioProgramme audioProgrammeID=\"APR_1003\" audioProgrammeName=\"ESC Netherlands Spanish\" audioProgrammeLanguage=\"spa\">\n"
"      <audioProgrammeLabel language=\"fre\">ESC Les Pays-Bas Espagnol</audioProgrammeLabel>\n"
"      <audioProgrammeLabel language=\"eng\">ESC Netherlands Spanish</audioProgrammeLabel>\n"
"      <audioContentIDRef>ACO_1001</audioContentIDRef>\n"
"      <audioContentIDRef>ACO_1004</audioContentIDRef>\n"
"    </audioProgramme>\n"
"    <audioProgramme audioProgrammeID=\"APR_1004\" audioProgrammeName=\"ESC Netherlands Portuguese\" audioProgrammeLanguage=\"por\">\n"
"      <audioProgrammeLabel language=\"fre\">ESC Les Pays-Bas Portugais</audioProgrammeLabel>\n"
"      <audioProgrammeLabel language=\"eng\">ESC Netherlands Portugese</audioProgrammeLabel>\n"
"      <audioContentIDRef>ACO_1001</audioContentIDRef>\n"
"      <audioContentIDRef>ACO_1005</audioContentIDRef>\n"
"    </audioProgramme>\n"
"    <audioProgramme audioProgrammeID=\"APR_1005\" audioProgrammeName=\"ESC Netherlands German\" audioProgrammeLanguage=\"ger\">\n"
"      <audioProgrammeLabel language=\"fre\">ESC Les Pays-Bas Allemand</audioProgrammeLabel>\n"
"      <audioProgrammeLabel language=\"eng\">ESC Netherlands German</audioProgrammeLabel>\n"
"      <audioContentIDRef>ACO_1001</audioContentIDRef>\n"
"      <audioContentIDRef>ACO_1006</audioContentIDRef>\n"
"    </audioProgramme>\n"
"    <audioContent audioContentID=\"ACO_1001\" audioContentName=\"mainPostcard\">\n"
"      <audioContentLabel language=\"fre\">Mix Principal</audioContentLabel>\n"
"      <audioContentLabel language=\"eng\">Main Mix</audioContentLabel>\n"
"      <dialogue mixedContentKind=\"2\">2</dialogue>\n"
"      <audioObjectIDRef>AO_1001</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioContent audioContentID=\"ACO_1002\" audioContentName=\"English\">\n"
"      <audioContentLabel language=\"fre\">Anglais</audioContentLabel>\n"
"      <audioContentLabel language=\"eng\">English</audioContentLabel>\n"
"      <dialogue dialogueContentKind=\"5\">1</dialogue>\n"
"      <audioObjectIDRef>AO_1002</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioContent audioContentID=\"ACO_1003\" audioContentName=\"French\">\n"
"      <audioContentLabel language=\"fre\">Francais</audioContentLabel>\n"
"      <audioContentLabel language=\"eng\">French</audioContentLabel>\n"
"      <dialogue dialogueContentKind=\"5\">1</dialogue>\n"
"      <audioObjectIDRef>AO_1003</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioContent audioContentID=\"ACO_1004\" audioContentName=\"Spanish\">\n"
"      <audioContentLabel language=\"fre\">Espagnol</audioContentLabel>\n"
"      <audioContentLabel language=\"eng\">Spanish</audioContentLabel>\n"
"      <dialogue dialogueContentKind=\"5\">1</dialogue>\n"
"      <audioObjectIDRef>AO_1004</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioContent audioContentID=\"ACO_1005\" audioContentName=\"Portuguese\">\n"
"      <audioContentLabel language=\"fre\">Portugais</audioContentLabel>\n"
"      <audioContentLabel language=\"eng\">Portugese</audioContentLabel>\n"
"      <dialogue dialogueContentKind=\"5\">1</dialogue>\n"
"      <audioObjectIDRef>AO_1005</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioContent audioContentID=\"ACO_1006\" audioContentName=\"German\">\n"
"      <audioContentLabel language=\"fre\">Allemand</audioContentLabel>\n"
"      <audioContentLabel language=\"eng\">German</audioContentLabel>\n"
"      <dialogue dialogueContentKind=\"5\">1</dialogue>\n"
"      <audioObjectIDRef>AO_1006</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioObject audioObjectID=\"AO_1001\" audioObjectName=\"mainPostcard\" lstart=\"00:00:00.00000\" lduration=\"00:00:00.02000\">\n"
"      <audioPackFormatIDRef>AP_00010005</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000003</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000004</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000005</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000006</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000007</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000008</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000009</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_0000000A</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioObject audioObjectID=\"AO_1002\" audioObjectName=\"English\" lstart=\"00:00:00.00000\" lduration=\"00:00:00.02000\">\n"
"      <audioPackFormatIDRef>AP_00010001</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_0000000B</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioObject audioObjectID=\"AO_1003\" audioObjectName=\"French\" lstart=\"00:00:00.00000\" lduration=\"00:00:00.02000\">\n"
"      <audioPackFormatIDRef>AP_00010001</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_0000000C</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioObject audioObjectID=\"AO_1004\" audioObjectName=\"Spanish\" lstart=\"00:00:00.00000\" lduration=\"00:00:00.02000\">\n"
"      <audioPackFormatIDRef>AP_00010001</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_0000000D</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioObject audioObjectID=\"AO_1005\" audioObjectName=\"Portuguese\" lstart=\"00:00:00.00000\" lduration=\"00:00:00.02000\">\n"
"      <audioPackFormatIDRef>AP_00010001</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_0000000E</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioObject audioObjectID=\"AO_1006\" audioObjectName=\"German\" lstart=\"00:00:00.00000\" lduration=\"00:00:00.02000\">\n"
"      <audioPackFormatIDRef>AP_00010001</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_0000000F</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioTrackUID UID=\"ATU_00000001\">\n"
"      <audioPackFormatIDRef>AP_00010005</audioPackFormatIDRef>\n"
"      <audioTrackFormatIDRef>AT_00010001_01</audioTrackFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000002\">\n"
"      <audioPackFormatIDRef>AP_00010005</audioPackFormatIDRef>\n"
"      <audioTrackFormatIDRef>AT_00010002_01</audioTrackFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000003\">\n"
"      <audioPackFormatIDRef>AP_00010005</audioPackFormatIDRef>\n"
"      <audioTrackFormatIDRef>AT_00010003_01</audioTrackFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000004\">\n"
"      <audioPackFormatIDRef>AP_00010005</audioPackFormatIDRef>\n"
"      <audioTrackFormatIDRef>AT_00010004_01</audioTrackFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000005\">\n"
"      <audioPackFormatIDRef>AP_00010005</audioPackFormatIDRef>\n"
"      <audioTrackFormatIDRef>AT_00010005_01</audioTrackFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000006\">\n"
"      <audioPackFormatIDRef>AP_00010005</audioPackFormatIDRef>\n"
"      <audioTrackFormatIDRef>AT_00010006_01</audioTrackFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000007\">\n"
"      <audioPackFormatIDRef>AP_00010005</audioPackFormatIDRef>\n"
"      <audioTrackFormatIDRef>AT_0001000D_01</audioTrackFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000008\">\n"
"      <audioPackFormatIDRef>AP_00010005</audioPackFormatIDRef>\n"
"      <audioTrackFormatIDRef>AT_0001000F_01</audioTrackFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000009\">\n"
"      <audioPackFormatIDRef>AP_00010005</audioPackFormatIDRef>\n"
"      <audioTrackFormatIDRef>AT_00010010_01</audioTrackFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_0000000A\">\n"
"      <audioPackFormatIDRef>AP_00010005</audioPackFormatIDRef>\n"
"      <audioTrackFormatIDRef>AT_00010012_01</audioTrackFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_0000000B\">\n"
"      <audioPackFormatIDRef>AP_00010001</audioPackFormatIDRef>\n"
"      <audioTrackFormatIDRef>AT_00010003_01</audioTrackFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_0000000C\">\n"
"      <audioPackFormatIDRef>AP_00010001</audioPackFormatIDRef>\n"
"      <audioTrackFormatIDRef>AT_00010003_01</audioTrackFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_0000000D\">\n"
"      <audioPackFormatIDRef>AP_00010001</audioPackFormatIDRef>\n"
"      <audioTrackFormatIDRef>AT_00010003_01</audioTrackFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_0000000E\">\n"
"      <audioPackFormatIDRef>AP_00010001</audioPackFormatIDRef>\n"
"      <audioTrackFormatIDRef>AT_00010003_01</audioTrackFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_0000000F\">\n"
"      <audioPackFormatIDRef>AP_00010001</audioPackFormatIDRef>\n"
"      <audioTrackFormatIDRef>AT_00010003_01</audioTrackFormatIDRef>\n"
"    </audioTrackUID>\n"
"  </audioFormatExtended>\n"
"</frame>\n"
;

static const char *stereo_2D_PMD GTEST_ATTRIBUTE_UNUSED_ =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<Smpte2109>\n"
"    <ContainerConfig>\n"
"        <SampleOffset>0</SampleOffset>\n"
"        <DynamicTags>\n"
"        </DynamicTags>\n"
"    </ContainerConfig>\n"
"    <ProfessionalMetadata version=\"11.0\">\n"
"        <Title>Small Stereo Program</Title>\n"
"        <AudioSignals>\n"
"            <AudioSignal id=\"1\">\n"
"                <Name>Signal 1</Name>\n"
"            </AudioSignal>\n"
"            <AudioSignal id=\"2\">\n"
"                <Name>Signal 2</Name>\n"
"            </AudioSignal>\n"
"            <AudioSignal id=\"3\">\n"
"                <Name>Signal 3</Name>\n"
"            </AudioSignal>\n"
"            <AudioSignal id=\"4\">\n"
"                <Name>Signal 4</Name>\n"
"            </AudioSignal>\n"
"        </AudioSignals>\n"
"        <AudioElements>\n"
"            <AudioBed id=\"1\">\n"
"                <Name>Stereo M+E</Name>\n"
"                <SpeakerConfig>2.0</SpeakerConfig>\n"
"                <OutputTargets>\n"
"                    <OutputTarget id=\"Left\">\n"
"                        <AudioSignals>\n"
"                            <ID>1</ID>\n"
"                        </AudioSignals>\n"
"                    </OutputTarget>\n"
"                    <OutputTarget id=\"Right\">\n"
"                        <AudioSignals>\n"
"                            <ID>2</ID>\n"
"                        </AudioSignals>\n"
"                    </OutputTarget>\n"
"                </OutputTargets>\n"
"            </AudioBed>\n"
"            <AudioObject id=\"2\">\n"
"                <Name>English Dialog</Name>\n"
"                <Class>Dialog</Class>\n"
"                <DynamicUpdates>False</DynamicUpdates>\n"
"                <X_Pos>0.00</X_Pos>\n"
"                <Y_Pos>1.00</Y_Pos>\n"
"                <Z_Pos>0.00</Z_Pos>\n"
"                <Size>0.00</Size>\n"
"                <Size_3D>False</Size_3D>\n"
"                <Diverge>False</Diverge>\n"
"                <AudioSignal>3</AudioSignal>\n"
"                <SourceGainDB>0.0dB</SourceGainDB>\n"
"            </AudioObject>\n"
"            <AudioObject id=\"3\">\n"
"                <Name>French Dialog</Name>\n"
"                <Class>Dialog</Class>\n"
"                <DynamicUpdates>False</DynamicUpdates>\n"
"                <X_Pos>0.00</X_Pos>\n"
"                <Y_Pos>1.00</Y_Pos>\n"
"                <Z_Pos>0.00</Z_Pos>\n"
"                <Size>0.00</Size>\n"
"                <Size_3D>False</Size_3D>\n"
"                <Diverge>False</Diverge>\n"
"                <AudioSignal>4</AudioSignal>\n"
"                <SourceGainDB>0.0dB</SourceGainDB>\n"
"            </AudioObject>\n"
"        </AudioElements>\n"
"        <Presentations>\n"
"            <Presentation id=\"1\">\n"
"                <Name language=\"en\">English</Name>\n"
"                <Name language=\"fr\">Anglais</Name>\n"
"                <Config>2.0 ME + D</Config>\n"
"                <Language>en</Language>\n"
"                <Element>1</Element>\n"
"                <Element>2</Element>\n"
"            </Presentation>\n"
"            <Presentation id=\"2\">\n"
"                <Name language=\"fr\">Francais</Name>\n"
"                <Name language=\"en\">French</Name>\n"
"                <Config>2.0 ME + D</Config>\n"
"                <Language>fr</Language>\n"
"                <Element>1</Element>\n"
"                <Element>3</Element>\n"
"            </Presentation>\n"
"        </Presentations>\n"
"        <EncoderConfigurations>\n"
"        </EncoderConfigurations>\n"
"        <IAT>\n"
"            <Content_ID><UUID>f8cc7821-09b2-41cb-bd42-ec35e9fcb9a8</UUID></Content_ID>\n"
"            <Timestamp>0</Timestamp>\n"
"        </IAT>\n"
"    </ProfessionalMetadata>\n"
"</Smpte2109>\n"
;

#endif  // DLB_ADM_UNIT_TEST_DATA_H
