/************************************************************************
 * dlb_adm
 * Copyright (c) 2020-2025, Dolby Laboratories Inc.
 * Copyright (c) 2020-2025, Dolby International AB.
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 **********************************************************************/

// This file is intended to be included in exactly one place, inside the
// AttributeDescriptor.cpp file.  It contains the initializer array for
// the attribute descriptors, in one location for easy editing.

static const AttributeInitializer initializers[] =
{
    /* xml */
    { DLB_ADM_ENTITY_TYPE_XML, "version",  DLB_ADM_TAG_XML_VERSION,  DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_XML, "encoding", DLB_ADM_TAG_XML_ENCODING, DLB_ADM_VALUE_TYPE_STRING },

    /* ituADM */
    { DLB_ADM_ENTITY_TYPE_ITU_ADM, "xmlns", DLB_ADM_TAG_ITU_ADM_XMLNS, DLB_ADM_VALUE_TYPE_STRING },

    /* frame */
    { DLB_ADM_ENTITY_TYPE_FRAME, "version", DLB_ADM_TAG_FRAME_VERSION, DLB_ADM_VALUE_TYPE_STRING },

    /* frameFormat */
    { DLB_ADM_ENTITY_TYPE_FRAME_FORMAT, "frameFormatID", DLB_ADM_TAG_FRAME_FORMAT_ID,             DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_FRAME_FORMAT, "type",          DLB_ADM_TAG_FRAME_FORMAT_TYPE,           DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_FRAME_FORMAT, "start",         DLB_ADM_TAG_FRAME_FORMAT_START,          DLB_ADM_VALUE_TYPE_TIME },
    { DLB_ADM_ENTITY_TYPE_FRAME_FORMAT, "duration",      DLB_ADM_TAG_FRAME_FORMAT_DURATION,       DLB_ADM_VALUE_TYPE_TIME },
    { DLB_ADM_ENTITY_TYPE_FRAME_FORMAT, "timeReference", DLB_ADM_TAG_FRAME_FORMAT_TIME_REFERENCE, DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_FRAME_FORMAT, "flowID",        DLB_ADM_TAG_FRAME_FORMAT_FLOW_ID,        DLB_ADM_VALUE_TYPE_STRING },

    /* transportTrackFormat */
    { DLB_ADM_ENTITY_TYPE_TRANSPORT_TRACK_FORMAT, "transportID",   DLB_ADM_TAG_TRANSPORT_TRACK_FORMAT_ID,         DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_TRANSPORT_TRACK_FORMAT, "transportName", DLB_ADM_TAG_TRANSPORT_TRACK_FORMAT_NAME,       DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_TRANSPORT_TRACK_FORMAT, "numIDs",        DLB_ADM_TAG_TRANSPORT_TRACK_FORMAT_NUM_IDS,    DLB_ADM_VALUE_TYPE_UINT },
    { DLB_ADM_ENTITY_TYPE_TRANSPORT_TRACK_FORMAT, "numTracks",     DLB_ADM_TAG_TRANSPORT_TRACK_FORMAT_NUM_TRACKS, DLB_ADM_VALUE_TYPE_UINT },

    /* audioProgramme */
    { DLB_ADM_ENTITY_TYPE_PROGRAMME, "audioProgrammeID",       DLB_ADM_TAG_PROGRAMME_ID,       DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_PROGRAMME, "audioProgrammeName",     DLB_ADM_TAG_PROGRAMME_NAME,     DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_PROGRAMME, "audioProgrammeLanguage", DLB_ADM_TAG_PROGRAMME_LANGUAGE, DLB_ADM_VALUE_TYPE_STRING },

    /* audioContent */
    { DLB_ADM_ENTITY_TYPE_CONTENT, "audioContentID",       DLB_ADM_TAG_CONTENT_ID,       DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_CONTENT, "audioContentName",     DLB_ADM_TAG_CONTENT_NAME,     DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_CONTENT, "audioContentLanguage", DLB_ADM_TAG_CONTENT_LANGUAGE, DLB_ADM_VALUE_TYPE_STRING },

    /* audioObject */
    { DLB_ADM_ENTITY_TYPE_OBJECT, "audioObjectID",   DLB_ADM_TAG_OBJECT_ID,         DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_OBJECT, "audioObjectName", DLB_ADM_TAG_OBJECT_NAME,       DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_OBJECT, "lstart",          DLB_ADM_TAG_OBJECT_L_START,    DLB_ADM_VALUE_TYPE_STRING /*DLB_ADM_VALUE_TYPE_TIME*/ },     // TODO
    { DLB_ADM_ENTITY_TYPE_OBJECT, "lduration",       DLB_ADM_TAG_OBJECT_L_DURATION, DLB_ADM_VALUE_TYPE_STRING /*DLB_ADM_VALUE_TYPE_TIME*/ },     // TODO
    { DLB_ADM_ENTITY_TYPE_OBJECT, "interact",        DLB_ADM_TAG_OBJECT_INTERACT,   DLB_ADM_VALUE_TYPE_BOOL },

    /* audioTrackUID */
    { DLB_ADM_ENTITY_TYPE_TRACK_UID, "UID",        DLB_ADM_TAG_TRACK_UID_UID,         DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_TRACK_UID, "sampleRate", DLB_ADM_TAG_TRACK_UID_SAMPLE_RATE, DLB_ADM_VALUE_TYPE_UINT },
    { DLB_ADM_ENTITY_TYPE_TRACK_UID, "bitDepth",   DLB_ADM_TAG_TRACK_UID_BIT_DEPTH,   DLB_ADM_VALUE_TYPE_UINT },

    /* audioPackFormat */
    { DLB_ADM_ENTITY_TYPE_PACK_FORMAT, "audioPackFormatID",   DLB_ADM_TAG_PACK_FORMAT_ID,              DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_PACK_FORMAT, "audioPackFormatName", DLB_ADM_TAG_PACK_FORMAT_NAME,            DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_PACK_FORMAT, "typeLabel",           DLB_ADM_TAG_PACK_FORMAT_TYPE_LABEL,      DLB_ADM_VALUE_TYPE_AUDIO_TYPE },
    { DLB_ADM_ENTITY_TYPE_PACK_FORMAT, "typeDefinition",      DLB_ADM_TAG_PACK_FORMAT_TYPE_DEFINITION, DLB_ADM_VALUE_TYPE_STRING },

    /* audioStreamFormat */
    { DLB_ADM_ENTITY_TYPE_STREAM_FORMAT, "audioStreamFormatID",   DLB_ADM_TAG_STREAM_FORMAT_ID,                DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_STREAM_FORMAT, "audioStreamFormatName", DLB_ADM_TAG_STREAM_FORMAT_NAME,              DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_STREAM_FORMAT, "formatLabel",           DLB_ADM_TAG_STREAM_FORMAT_FORMAT_LABEL,      DLB_ADM_VALUE_TYPE_AUDIO_TYPE },
    { DLB_ADM_ENTITY_TYPE_STREAM_FORMAT, "formatDefinition",      DLB_ADM_TAG_STREAM_FORMAT_FORMAT_DEFINITION, DLB_ADM_VALUE_TYPE_STRING },

    /* audioChannelFormat */
    { DLB_ADM_ENTITY_TYPE_CHANNEL_FORMAT, "audioChannelFormatID",   DLB_ADM_TAG_CHANNEL_FORMAT_ID,              DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_CHANNEL_FORMAT, "audioChannelFormatName", DLB_ADM_TAG_CHANNEL_FORMAT_NAME,            DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_CHANNEL_FORMAT, "typeLabel",              DLB_ADM_TAG_CHANNEL_FORMAT_TYPE_LABEL,      DLB_ADM_VALUE_TYPE_AUDIO_TYPE },
    { DLB_ADM_ENTITY_TYPE_CHANNEL_FORMAT, "typeDefinition",         DLB_ADM_TAG_CHANNEL_FORMAT_TYPE_DEFINITION, DLB_ADM_VALUE_TYPE_STRING },

    /* audioTrackFormat */
    { DLB_ADM_ENTITY_TYPE_TRACK_FORMAT, "audioTrackFormatID",   DLB_ADM_TAG_TRACK_FORMAT_ID,                DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_TRACK_FORMAT, "audioTrackFormatName", DLB_ADM_TAG_TRACK_FORMAT_NAME,              DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_TRACK_FORMAT, "formatLabel",          DLB_ADM_TAG_TRACK_FORMAT_FORMAT_LABEL,      DLB_ADM_VALUE_TYPE_AUDIO_TYPE },
    { DLB_ADM_ENTITY_TYPE_TRACK_FORMAT, "formatDefinition",     DLB_ADM_TAG_TRACK_FORMAT_FORMAT_DEFINITION, DLB_ADM_VALUE_TYPE_STRING },

    /* audioBlockFormat */
    { DLB_ADM_ENTITY_TYPE_BLOCK_FORMAT, "audioBlockFormatID", DLB_ADM_TAG_BLOCK_FORMAT_ID,        DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_BLOCK_FORMAT, "rtime",              DLB_ADM_TAG_BLOCK_FORMAT_RTIME,     DLB_ADM_VALUE_TYPE_TIME },
    { DLB_ADM_ENTITY_TYPE_BLOCK_FORMAT, "duration",           DLB_ADM_TAG_BLOCK_FORMAT_DURATION,  DLB_ADM_VALUE_TYPE_TIME },
    { DLB_ADM_ENTITY_TYPE_BLOCK_FORMAT, "lstart",             DLB_ADM_TAG_BLOCK_FORMAT_LSTART,    DLB_ADM_VALUE_TYPE_TIME },
    { DLB_ADM_ENTITY_TYPE_BLOCK_FORMAT, "lduration",          DLB_ADM_TAG_BLOCK_FORMAT_LDURATION, DLB_ADM_VALUE_TYPE_TIME },

    /* alternativeValueSet */
    { DLB_ADM_ENTITY_TYPE_ALT_VALUE_SET, "alternativeValueSetID", DLB_ADM_TAG_ALT_VALUE_SET_ID, DLB_ADM_VALUE_TYPE_STRING },
    // TODO...

    /* audioTrack */
    { DLB_ADM_ENTITY_TYPE_AUDIO_TRACK, "trackID",           DLB_ADM_TAG_AUDIO_TRACK_ID,                 DLB_ADM_VALUE_TYPE_UINT },
    { DLB_ADM_ENTITY_TYPE_AUDIO_TRACK, "formatLabel",       DLB_ADM_TAG_AUDIO_TRACK_FORMAT_LABEL,       DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_AUDIO_TRACK, "formatDefinition",  DLB_ADM_TAG_AUDIO_TRACK_FORMAT_DEFINITION,  DLB_ADM_VALUE_TYPE_STRING },

    /* audioFormatExtended */
    { DLB_ADM_ENTITY_TYPE_AUDIO_FORMAT_EXTENDED, "version", DLB_ADM_TAG_AUDIO_FORMAT_EXT_VERSION, DLB_ADM_VALUE_TYPE_STRING },

    /* profile (profileList) */
    { DLB_ADM_ENTITY_TYPE_PROFILE_LIST_SPECIFICATION, "profileListSpecValue", DLB_ADM_TAG_PROFILE_LIST_SPECIFICATION_VALUE,     DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_PROFILE_LIST_SPECIFICATION, "profileName",          DLB_ADM_TAG_PROFILE_LIST_SPECIFICATION_NAME,      DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_PROFILE_LIST_SPECIFICATION, "profileVersion",       DLB_ADM_TAG_PROFILE_LIST_SPECIFICATION_VERSION,   DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_PROFILE_LIST_SPECIFICATION, "profileLevel",         DLB_ADM_TAG_PROFILE_LIST_SPECIFICATION_LEVEL,     DLB_ADM_VALUE_TYPE_STRING },

    /* audioProgrammeLabel */
    { DLB_ADM_ENTITY_TYPE_PROGRAMME_LABEL, "audioProgrammeLabelValue", DLB_ADM_TAG_PROGRAMME_LABEL_VALUE,    DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_PROGRAMME_LABEL, "language",                 DLB_ADM_TAG_PROGRAMME_LABEL_LANGUAGE, DLB_ADM_VALUE_TYPE_STRING },

    /* audioContentLabel */
    { DLB_ADM_ENTITY_TYPE_CONTENT_LABEL, "audioContentLabelValue", DLB_ADM_TAG_CONTENT_LABEL_VALUE,    DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_CONTENT_LABEL, "language",               DLB_ADM_TAG_CONTENT_LABEL_LANGUAGE, DLB_ADM_VALUE_TYPE_STRING },

    /* audioObjectLabel */
    { DLB_ADM_ENTITY_TYPE_OBJECT_LABEL, "audioObjectLabelValue", DLB_ADM_TAG_OBJECT_LABEL_VALUE,    DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_OBJECT_LABEL, "language",              DLB_ADM_TAG_OBJECT_LABEL_LANGUAGE, DLB_ADM_VALUE_TYPE_STRING },

    /* gain */
    { DLB_ADM_ENTITY_TYPE_GAIN, "gainValue", DLB_ADM_TAG_SPEAKER_GAIN_VALUE, DLB_ADM_VALUE_TYPE_FLOAT },
    { DLB_ADM_ENTITY_TYPE_GAIN, "gainUnit",  DLB_ADM_TAG_SPEAKER_GAIN_UNIT,  DLB_ADM_VALUE_TYPE_STRING },

    /* speakerLabel */
    { DLB_ADM_ENTITY_TYPE_SPEAKER_LABEL, "speakerLabelValue", DLB_ADM_TAG_SPEAKER_LABEL_VALUE, DLB_ADM_VALUE_TYPE_STRING },

    /* dialogue */
    { DLB_ADM_ENTITY_TYPE_DIALOGUE, "dialogueValue",          DLB_ADM_TAG_DIALOGUE_VALUE,             DLB_ADM_VALUE_TYPE_UINT },
    { DLB_ADM_ENTITY_TYPE_DIALOGUE, "nonDialogueContentKind", DLB_ADM_TAG_DIALOGUE_NON_DIALOGUE_KIND, DLB_ADM_VALUE_TYPE_UINT },
    { DLB_ADM_ENTITY_TYPE_DIALOGUE, "dialogueContentKind",    DLB_ADM_TAG_DIALOGUE_DIALOGUE_KIND,     DLB_ADM_VALUE_TYPE_UINT },
    { DLB_ADM_ENTITY_TYPE_DIALOGUE, "mixedContentKind",       DLB_ADM_TAG_DIALOGUE_MIXED_KIND,        DLB_ADM_VALUE_TYPE_UINT },

    /* cartesian */
    { DLB_ADM_ENTITY_TYPE_CARTESIAN, "cartesianValue", DLB_ADM_TAG_CARTESIAN_VALUE, DLB_ADM_VALUE_TYPE_BOOL },

    /* position */
    { DLB_ADM_ENTITY_TYPE_POSITION, "positionValue",  DLB_ADM_TAG_POSITION_VALUE,            DLB_ADM_VALUE_TYPE_FLOAT },
    { DLB_ADM_ENTITY_TYPE_POSITION, "coordinate",     DLB_ADM_TAG_POSITION_COORDINATE,       DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_POSITION, "screenEdgeLock", DLB_ADM_TAG_POSITION_SCREEN_EDGE_LOCK, DLB_ADM_VALUE_TYPE_STRING },

    /* equation */
    { DLB_ADM_ENTITY_TYPE_EQUATION, "equationValue", DLB_ADM_TAG_EQUATION_VALUE, DLB_ADM_VALUE_TYPE_STRING },

    /* degree */
    { DLB_ADM_ENTITY_TYPE_DEGREE, "degreeValue", DLB_ADM_TAG_DEGREE_VALUE, DLB_ADM_VALUE_TYPE_INT },

    /* order */
    { DLB_ADM_ENTITY_TYPE_ORDER, "orderValue", DLB_ADM_TAG_ORDER_VALUE, DLB_ADM_VALUE_TYPE_UINT },

    /* normalization */
    { DLB_ADM_ENTITY_TYPE_NORMALIZATION, "normalizationValue", DLB_ADM_TAG_NORMALIZATION_VALUE, DLB_ADM_VALUE_TYPE_STRING },

    /* frequency */
    { DLB_ADM_ENTITY_TYPE_FREQUENCY, "frequencyValue", DLB_ADM_TAG_FREQUENCY_VALUE,           DLB_ADM_VALUE_TYPE_FLOAT },
    { DLB_ADM_ENTITY_TYPE_FREQUENCY, "typeDefinition", DLB_ADM_TAG_FREQUENCY_TYPE_DEFINITION, DLB_ADM_VALUE_TYPE_STRING },

    /* audioObjectInteraction */
    { DLB_ADM_ENTITY_TYPE_OBJECT_INTERACTION, "onOffInteract",      DLB_ADM_TAG_OBJECT_INTERACTION_ON_OFF,      DLB_ADM_VALUE_TYPE_BOOL },
    { DLB_ADM_ENTITY_TYPE_OBJECT_INTERACTION, "gainInteract",       DLB_ADM_TAG_OBJECT_INTERACTION_GAIN,        DLB_ADM_VALUE_TYPE_BOOL },
    { DLB_ADM_ENTITY_TYPE_OBJECT_INTERACTION, "positionInteract",   DLB_ADM_TAG_OBJECT_INTERACTION_POSITION,    DLB_ADM_VALUE_TYPE_BOOL },

    /* gainInteractionRange */
    { DLB_ADM_ENTITY_TYPE_GAIN_INTERACTION_RANGE, "gainInteractionRangeValue",  DLB_ADM_TAG_GAIN_INTERACTION_RANGE_VALUE,   DLB_ADM_VALUE_TYPE_FLOAT },
    { DLB_ADM_ENTITY_TYPE_GAIN_INTERACTION_RANGE, "bound",                      DLB_ADM_TAG_GAIN_INTERACTION_RANGE_BOUND,   DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_GAIN_INTERACTION_RANGE, "gainUnit",                   DLB_ADM_TAG_GAIN_INTERACTION_RANGE_UNIT,    DLB_ADM_VALUE_TYPE_STRING },

    /* positionInteractionRange */
    { DLB_ADM_ENTITY_TYPE_POSITION_INTERACTION_RANGE, "positionInteractionRangeValue",  DLB_ADM_TAG_POSITION_INTERACTION_RANGE_VALUE,       DLB_ADM_VALUE_TYPE_FLOAT },
    { DLB_ADM_ENTITY_TYPE_POSITION_INTERACTION_RANGE, "bound",                          DLB_ADM_TAG_POSITION_INTERACTION_RANGE_BOUND,       DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_POSITION_INTERACTION_RANGE, "coordinate",                     DLB_ADM_TAG_POSITION_INTERACTION_RANGE_COORDINATE,  DLB_ADM_VALUE_TYPE_STRING },

    /* positionOffset */
    { DLB_ADM_ENTITY_TYPE_POSITION_OFFSET, "positionOffsetValue",   DLB_ADM_TAG_POSITION_OFFSET_VALUE,      DLB_ADM_VALUE_TYPE_FLOAT },
    { DLB_ADM_ENTITY_TYPE_POSITION_OFFSET, "coordinate",            DLB_ADM_TAG_POSITION_OFFSET_COORDINATE, DLB_ADM_VALUE_TYPE_STRING },

    /* audioFormatCustomSet */
    { DLB_ADM_ENTITY_TYPE_FORMAT_CUSTOM_SET, "audioFormatCustomSetID",      DLB_ADM_TAG_FORMAT_CUSTOM_SET_ID,       DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_FORMAT_CUSTOM_SET, "audioFormatCustomSetName",    DLB_ADM_TAG_FORMAT_CUSTOM_SET_NAME,     DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_FORMAT_CUSTOM_SET, "audioFormatCustomSetType",    DLB_ADM_TAG_FORMAT_CUSTOM_SET_TYPE,     DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_FORMAT_CUSTOM_SET, "audioFormatCustomSetVersion", DLB_ADM_TAG_FORMAT_CUSTOM_SET_VERSION,  DLB_ADM_VALUE_TYPE_STRING },

    /* profile (admInformation) */
    { DLB_ADM_ENTITY_TYPE_PROFILE, "levelID",           DLB_ADM_TAG_PROFILE_LEVEL_ID,   DLB_ADM_VALUE_TYPE_UINT },
    { DLB_ADM_ENTITY_TYPE_PROFILE, "profileName",       DLB_ADM_TAG_PROFILE_NAME,       DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_PROFILE, "profileVersion",    DLB_ADM_TAG_PROFILE_VERSION,    DLB_ADM_VALUE_TYPE_STRING },

    /* loudnessMetadata */
    { DLB_ADM_ENTITY_TYPE_LOUDNESS_METADATA, "loudnessMethod", DLB_ADM_TAG_LOUDNESS_METHOD, DLB_ADM_VALUE_TYPE_STRING },

    /* integratedLoundess */
    { DLB_ADM_ENTITY_TYPE_INTEGRATED_LOUDNESS, "integratedLoudness", DLB_ADM_TAG_INTEGRATED_LOUDNESS_VALUE, DLB_ADM_VALUE_TYPE_FLOAT },

    /* dialogueLoundess */
    { DLB_ADM_ENTITY_TYPE_DIALOGUE_LOUDNESS, "dialogueLoudness", DLB_ADM_TAG_DIALOGUE_LOUDNESS_VALUE, DLB_ADM_VALUE_TYPE_FLOAT },

    /* audioComplementaryObjectGroupLabel */
    { DLB_ADM_ENTITY_TYPE_COMPLEMENTARY_OBJECT_GROUP_LABEL, "audioComplementaryObjectGroupLabelValue",  DLB_ADM_TAG_COMPLEMENTARY_OBJECT_GROUP_LABEL_VALUE,     DLB_ADM_VALUE_TYPE_STRING },
    { DLB_ADM_ENTITY_TYPE_COMPLEMENTARY_OBJECT_GROUP_LABEL, "language",                                 DLB_ADM_TAG_COMPLEMENTARY_OBJECT_GROUP_LABEL_LANGUAGE,  DLB_ADM_VALUE_TYPE_STRING },

    { DLB_ADM_ENTITY_TYPE_COMPLEMENTARY_OBJECT_REF,         "audioComplementaryObjectIDRefValue",       DLB_ADM_TAG_COMPLEMENTARY_OBJECT_ID_REF,                DLB_ADM_VALUE_TYPE_REF },

    { DLB_ADM_ENTITY_TYPE_METADATA_SEGMENT, "ID",           DLB_ADM_TAG_METADATA_SEGMENT_ID,   DLB_ADM_VALUE_TYPE_UINT },
    { DLB_ADM_ENTITY_TYPE_DOLBY_E, "ID",                    DLB_ADM_TAG_DOLBY_E_ID,   DLB_ADM_VALUE_TYPE_UINT },

    { DLB_ADM_ENTITY_TYPE_PROGRAM_CONFIG, "programConfig", DLB_ADM_TAG_PROGRAM_CONFIG_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_FRAME_RATE_CODE, "frameRateCode", DLB_ADM_TAG_FRAME_RATE_CODE_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_SMPTE_TIME_CODE, "smpteTimeCode", DLB_ADM_TAG_SMPTE_TIME_CODE_VALUE, DLB_ADM_VALUE_TYPE_STRING},

    { DLB_ADM_ENTITY_TYPE_AC3_PROGRAM, "ID", DLB_ADM_TAG_AC3_PROGRAM_ID,   DLB_ADM_VALUE_TYPE_UINT },
    { DLB_ADM_ENTITY_TYPE_ACMOD, "acMod", DLB_ADM_TAG_ACMOD_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_BSMOD, "bsMod", DLB_ADM_TAG_BSMOD_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_LFEON, "lfeOn", DLB_ADM_TAG_LFEON_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_CMIXLEV, "cMixLev", DLB_ADM_TAG_CMIXLEV_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_SURMIXLEV, "surMixLev", DLB_ADM_TAG_SURMIXLEV_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_DSURMOD, "dSurMod", DLB_ADM_TAG_DSURMOD_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_DIALNORM, "dialNorm", DLB_ADM_TAG_DIALNORM_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_COPYRIGHTB, "copyRightB", DLB_ADM_TAG_COPYRIGHTB_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_ORIGBS, "origBs", DLB_ADM_TAG_ORIGBS_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_LANG_CODE, "exists", DLB_ADM_TAG_LANG_CODE_EXIST, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_LANG_COD, "langCod", DLB_ADM_TAG_LANG_COD_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_AUDIO_PROD_INFO, "exists", DLB_ADM_TAG_AUDIO_PROD_INFO_EXIST, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_MIXLEVEL, "mixLevel", DLB_ADM_TAG_MIXLEVEL_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_ROOMTYP, "roomTyp", DLB_ADM_TAG_ROOMTYP_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_EXTBSI1E, "exists", DLB_ADM_TAG_EXTBSI1E_EXIST, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_LORO_CMIXLEV, "loRoCMixLev", DLB_ADM_TAG_LORO_CMIXLEV_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_LORO_SURMIXLEV, "loRoSurMixLev", DLB_ADM_TAG_LORO_SURMIXLEV_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_LTRT_CMIXLEV, "ltRtCMixLev", DLB_ADM_TAG_LTRT_CMIXLEV_VALUE, DLB_ADM_VALUE_TYPE_UINT}, 
    { DLB_ADM_ENTITY_TYPE_LTRT_SURMIXLEV, "ltRtSurMixLev", DLB_ADM_TAG_LTRT_SURMIXLEV_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_DMIXMOD, "dMixMod", DLB_ADM_TAG_DMIXMOD_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_EXTBSI2E, "exists", DLB_ADM_TAG_EXTBSI2E_EXIST, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_DSUREXMOD, "dSurExMod", DLB_ADM_TAG_DSUREXMOD_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_DHEADPHONMOD, "dHeadPhonMod", DLB_ADM_TAG_DHEADPHONMOD_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_ADCONVTYP, "adConvTyp", DLB_ADM_TAG_ADCONVTYP_VALUE, DLB_ADM_VALUE_TYPE_UINT},       
    { DLB_ADM_ENTITY_TYPE_LANG_COD, "langCod", DLB_ADM_TAG_LANG_COD_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_COMPR1, "exists", DLB_ADM_TAG_COMPR1_EXIST, DLB_ADM_VALUE_TYPE_UINT},    
    { DLB_ADM_ENTITY_TYPE_COMPR1, "compr1", DLB_ADM_TAG_COMPR1_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_DYNRNG1, "exists", DLB_ADM_TAG_DYNRNG1_EXIST, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_DYNRNG1, "dynRng1", DLB_ADM_TAG_DYNRNG1_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_PROGRAM_DESCRIPTION_TEXT, "programDescriptionText", DLB_ADM_TAG_PROGRAM_DESCRIPTION_TEXT_VALUE, DLB_ADM_VALUE_TYPE_STRING},                  

    { DLB_ADM_ENTITY_TYPE_ENCODE_PARAMETERS, "ID", DLB_ADM_TAG_ENCODE_PARAMETERS_ID,   DLB_ADM_VALUE_TYPE_UINT },
    { DLB_ADM_ENTITY_TYPE_HPFON, "hpFOn", DLB_ADM_TAG_HPFON_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_BWLPFON, "bwLpFOn", DLB_ADM_TAG_BWLPFON_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_LFELPFON, "lfeLpFOn", DLB_ADM_TAG_LFELPFON_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_SUR90ON, "sur90On", DLB_ADM_TAG_SUR90ON_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_SURRATTON, "surAttOn", DLB_ADM_TAG_SURRATTON_VALUE, DLB_ADM_VALUE_TYPE_UINT},
    { DLB_ADM_ENTITY_TYPE_RFPREMPHON, "rfPremphOn", DLB_ADM_TAG_RFPREMPHON_VALUE, DLB_ADM_VALUE_TYPE_UINT}         
};
