/************************************************************************
 * dlb_adm
 * Copyright (c) 2020-2025, Dolby Laboratories Inc.
 * Copyright (c) 2020-2025, Dolby International AB.
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 **********************************************************************/

// This file is intended to be included in exactly one place, inside the
// EntityDescriptor.cpp file.  It contains the initializer array for
// the entity descriptors, in one location for easy editing.

static const EntityDescriptor initializers[] =
{
    {
        "___void___",
        DLB_ADM_ENTITY_TYPE_VOID,
        false,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "___toplevel___",
        DLB_ADM_ENTITY_TYPE_TOPLEVEL,
        false,
        true,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "xml",
        DLB_ADM_ENTITY_TYPE_XML,
        false,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },

    // IDRef entities...
    {
        "audioProgrammeIDRef",
        DLB_ADM_ENTITY_TYPE_PROGRAMME,
        false,
        true,
        true,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "audioContentIDRef",
        DLB_ADM_ENTITY_TYPE_CONTENT,
        false,
        true,
        true,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "audioObjectIDRef",
        DLB_ADM_ENTITY_TYPE_OBJECT,
        false,
        true,
        true,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "audioPackFormatIDRef",
        DLB_ADM_ENTITY_TYPE_PACK_FORMAT,
        false,
        true,
        true,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "audioTrackUIDRef",
        DLB_ADM_ENTITY_TYPE_TRACK_UID,
        false,
        true,
        true,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "audioChannelFormatIDRef",
        DLB_ADM_ENTITY_TYPE_CHANNEL_FORMAT,
        false,
        true,
        true,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "audioStreamFormatIDRef",
        DLB_ADM_ENTITY_TYPE_STREAM_FORMAT,
        false,
        true,
        true,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "audioTrackFormatIDRef",
        DLB_ADM_ENTITY_TYPE_TRACK_FORMAT,
        false,
        true,
        true,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "audioComplementaryObjectIDRef",
        DLB_ADM_ENTITY_TYPE_COMPLEMENTARY_OBJECT_REF,
        false,
        false,
        false,
        DLB_ADM_TAG_COMPLEMENTARY_OBJECT_ID_REF
    },
    {
        "alternativeValueSetIDRef",
        DLB_ADM_ENTITY_TYPE_ALT_VALUE_SET,
        false,
        true,
        true,
        DLB_ADM_TAG_UNKNOWN
    },
    // ... IDRef entities

    // Entities with ADM identifiers...
    {
        "frameFormat",
        DLB_ADM_ENTITY_TYPE_FRAME_FORMAT,
        true,
        true,
        false,
        DLB_ADM_TAG_FRAME_FORMAT_ID
    },
    {
        "transportTrackFormat",
        DLB_ADM_ENTITY_TYPE_TRANSPORT_TRACK_FORMAT,
        true,
        true,
        false,
        DLB_ADM_TAG_TRANSPORT_TRACK_FORMAT_ID
    },
    {
        "audioProgramme",
        DLB_ADM_ENTITY_TYPE_PROGRAMME,
        true,
        true,
        false,
        DLB_ADM_TAG_PROGRAMME_ID
    },
    {
        "audioContent",
        DLB_ADM_ENTITY_TYPE_CONTENT,
        true,
        true,
        false,
        DLB_ADM_TAG_CONTENT_ID
    },
    {
        "audioObject",
        DLB_ADM_ENTITY_TYPE_OBJECT,
        true,
        true,
        false,
        DLB_ADM_TAG_OBJECT_ID
    },
    {
        "audioTrackUID",
        DLB_ADM_ENTITY_TYPE_TRACK_UID,
        true,
        true,
        false,
        DLB_ADM_TAG_TRACK_UID_UID
    },
    {
        "audioPackFormat",
        DLB_ADM_ENTITY_TYPE_PACK_FORMAT,
        true,
        true,
        false,
        DLB_ADM_TAG_PACK_FORMAT_ID
    },
    {
        "audioStreamFormat",
        DLB_ADM_ENTITY_TYPE_STREAM_FORMAT,
        true,
        true,
        false,
        DLB_ADM_TAG_STREAM_FORMAT_ID
    },
    {
        "audioChannelFormat",
        DLB_ADM_ENTITY_TYPE_CHANNEL_FORMAT,
        true,
        true,
        false,
        DLB_ADM_TAG_CHANNEL_FORMAT_ID
    },
    {
        "audioTrackFormat",
        DLB_ADM_ENTITY_TYPE_TRACK_FORMAT,
        true,
        true,
        false,
        DLB_ADM_TAG_TRACK_FORMAT_ID
    },
    {
        "audioBlockFormat",
        DLB_ADM_ENTITY_TYPE_BLOCK_FORMAT,
        true,
        true,
        false,
        DLB_ADM_TAG_BLOCK_FORMAT_ID
    },
    {
        "alternativeValueSet",
        DLB_ADM_ENTITY_TYPE_ALT_VALUE_SET,
        true,
        true,
        false,
        DLB_ADM_TAG_ALT_VALUE_SET_ID
    },
    {
        "audioFormatCustomSet",
        DLB_ADM_ENTITY_TYPE_FORMAT_CUSTOM_SET,
        true,
        true,
        false,
        DLB_ADM_TAG_FORMAT_CUSTOM_SET_ID
    },
    // ... entities with ADM identifiers

    // Component entities (no ADM identifier)...
    {
        "ituADM",
        DLB_ADM_ENTITY_TYPE_ITU_ADM,
        true,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "coreMetadata",
        DLB_ADM_ENTITY_TYPE_CORE_METADATA,
        true,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "format",
        DLB_ADM_ENTITY_TYPE_FORMAT,
        true,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "frame",
        DLB_ADM_ENTITY_TYPE_FRAME,
        true,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "frameHeader",
        DLB_ADM_ENTITY_TYPE_FRAME_HEADER,
        true,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "profileList",
        DLB_ADM_ENTITY_TYPE_PROFILE_LIST,
        true,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "profile",
        DLB_ADM_ENTITY_TYPE_PROFILE_LIST_SPECIFICATION,
        false,
        false,
        false,
        DLB_ADM_TAG_PROFILE_LIST_SPECIFICATION_VALUE
    },
    {
        "changedIDs",
        DLB_ADM_ENTITY_TYPE_CHANGED_IDS,
        true,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "audioTrack",
        DLB_ADM_ENTITY_TYPE_AUDIO_TRACK,
        true,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "audioFormatExtended",
        DLB_ADM_ENTITY_TYPE_AUDIO_FORMAT_EXTENDED,
        true,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "audioProgrammeLabel",
        DLB_ADM_ENTITY_TYPE_PROGRAMME_LABEL,
        false,
        false,
        false,
        DLB_ADM_TAG_PROGRAMME_LABEL_VALUE
    },
    {
        "audioContentLabel",
        DLB_ADM_ENTITY_TYPE_CONTENT_LABEL,
        false,
        false,
        false,
        DLB_ADM_TAG_CONTENT_LABEL_VALUE
    },
    {
        "audioObjectLabel",
        DLB_ADM_ENTITY_TYPE_OBJECT_LABEL,
        false,
        false,
        false,
        DLB_ADM_TAG_OBJECT_LABEL_VALUE
    },
    {
        "gain",
        DLB_ADM_ENTITY_TYPE_GAIN,
        false,
        false,
        false,
        DLB_ADM_TAG_SPEAKER_GAIN_VALUE
    },
    {
        "speakerLabel",
        DLB_ADM_ENTITY_TYPE_SPEAKER_LABEL,
        false,
        false,
        false,
        DLB_ADM_TAG_SPEAKER_LABEL_VALUE
    },
    {
        "dialogue",
        DLB_ADM_ENTITY_TYPE_DIALOGUE,
        false,
        false,
        false,
        DLB_ADM_TAG_DIALOGUE_VALUE
    },
    {
        "cartesian",
        DLB_ADM_ENTITY_TYPE_CARTESIAN,
        false,
        false,
        false,
        DLB_ADM_TAG_CARTESIAN_VALUE
    },
    {
        "position",
        DLB_ADM_ENTITY_TYPE_POSITION,
        false,
        false,
        false,
        DLB_ADM_TAG_POSITION_VALUE
    },
    {
        "equation",
        DLB_ADM_ENTITY_TYPE_EQUATION,
        false,
        false,
        false,
        DLB_ADM_TAG_EQUATION_VALUE
    },
    {
        "degree",
        DLB_ADM_ENTITY_TYPE_DEGREE,
        false,
        false,
        false,
        DLB_ADM_TAG_DEGREE_VALUE
    },
    {
        "order",
        DLB_ADM_ENTITY_TYPE_ORDER,
        false,
        false,
        false,
        DLB_ADM_TAG_ORDER_VALUE
    },
    {
        "normalization",
        DLB_ADM_ENTITY_TYPE_NORMALIZATION,
        false,
        false,
        false,
        DLB_ADM_TAG_NORMALIZATION_VALUE
    },
    {
        "frequency",
        DLB_ADM_ENTITY_TYPE_FREQUENCY,
        false,
        false,
        false,
        DLB_ADM_TAG_FREQUENCY_VALUE
    },
    {
        "audioObjectInteraction",
        DLB_ADM_ENTITY_TYPE_OBJECT_INTERACTION,
        true,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "gainInteractionRange",
        DLB_ADM_ENTITY_TYPE_GAIN_INTERACTION_RANGE,
        false,
        false,
        false,
        DLB_ADM_TAG_GAIN_INTERACTION_RANGE_VALUE
    },
    {
        "positionInteractionRange",
        DLB_ADM_ENTITY_TYPE_POSITION_INTERACTION_RANGE,
        false,
        false,
        false,
        DLB_ADM_TAG_POSITION_INTERACTION_RANGE_VALUE
    },
    {
        "positionOffset",
        DLB_ADM_ENTITY_TYPE_POSITION_OFFSET,
        false,
        false,
        false,
        DLB_ADM_TAG_POSITION_OFFSET_VALUE
    },
    {
        "audioFormatCustom",
        DLB_ADM_ENTITY_TYPE_FORMAT_CUSTOM,
        true,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "admInformation",
        DLB_ADM_ENTITY_TYPE_ADM_INFORMATION,
        true,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "profile",
        DLB_ADM_ENTITY_TYPE_PROFILE,
        false,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "loudnessMetadata",
        DLB_ADM_ENTITY_TYPE_LOUDNESS_METADATA,
        true,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "integratedLoudness",
        DLB_ADM_ENTITY_TYPE_INTEGRATED_LOUDNESS,
        false,
        false,
        false,
        DLB_ADM_TAG_INTEGRATED_LOUDNESS_VALUE
    },
    {
        "dialogueLoudness",
        DLB_ADM_ENTITY_TYPE_DIALOGUE_LOUDNESS,
        false,
        false,
        false,
        DLB_ADM_TAG_DIALOGUE_LOUDNESS_VALUE
    },
    {
        "audioComplementaryObjectGroupLabel",
        DLB_ADM_ENTITY_TYPE_COMPLEMENTARY_OBJECT_GROUP_LABEL,
        false,
        false,
        false,
        DLB_ADM_TAG_COMPLEMENTARY_OBJECT_GROUP_LABEL_VALUE
    },
    {
        "dbmd",
        DLB_ADM_ENTITY_TYPE_DBMD,
        true,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "metadataSegment",
        DLB_ADM_ENTITY_TYPE_METADATA_SEGMENT,
        true,
        false,
        false,
        DLB_ADM_TAG_METADATA_SEGMENT_ID
    },  
    {
        "dolbyE",
        DLB_ADM_ENTITY_TYPE_DOLBY_E,
        true,
        false,
        false,
        DLB_ADM_TAG_DOLBY_E_ID
    },
    {
        "programConfig",
        DLB_ADM_ENTITY_TYPE_PROGRAM_CONFIG,
        false,
        false,
        false,
        DLB_ADM_TAG_PROGRAM_CONFIG_VALUE
    },
    {
        "frameRateCode",
        DLB_ADM_ENTITY_TYPE_FRAME_RATE_CODE,
        false,
        false,
        false,
        DLB_ADM_TAG_FRAME_RATE_CODE_VALUE
    },
    {
        "smpteTimeCode",
        DLB_ADM_ENTITY_TYPE_SMPTE_TIME_CODE,
        false,
        false,
        false,
        DLB_ADM_TAG_SMPTE_TIME_CODE_VALUE
    },
    {
        "ac3Program",
        DLB_ADM_ENTITY_TYPE_AC3_PROGRAM,
        true,
        false,
        false,
        DLB_ADM_TAG_AC3_PROGRAM_ID
    },
    {
        "programInfo",
        DLB_ADM_ENTITY_TYPE_PROGRAM_INFO,
        true,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "acMod",
        DLB_ADM_ENTITY_TYPE_ACMOD,
        false,
        false,
        false,
        DLB_ADM_TAG_ACMOD_VALUE
    },
    {
        "bsMod",
        DLB_ADM_ENTITY_TYPE_BSMOD,
        false,
        false,
        false,
        DLB_ADM_TAG_BSMOD_VALUE
    },
    {
        "lfeOn",
        DLB_ADM_ENTITY_TYPE_LFEON,
        false,
        false,
        false,
        DLB_ADM_TAG_LFEON_VALUE
    },
    {
        "cMixLev",
        DLB_ADM_ENTITY_TYPE_CMIXLEV,
        false,
        false,
        false,
        DLB_ADM_TAG_CMIXLEV_VALUE
    },
    {
        "surMixLev",
        DLB_ADM_ENTITY_TYPE_SURMIXLEV,
        false,
        false,
        false,
        DLB_ADM_TAG_SURMIXLEV_VALUE
    },
    {
        "dSurMod",
        DLB_ADM_ENTITY_TYPE_DSURMOD,
        false,
        false,
        false,
        DLB_ADM_TAG_DSURMOD_VALUE
    },
    {
        "dialNorm",
        DLB_ADM_ENTITY_TYPE_DIALNORM,
        false,
        false,
        false,
        DLB_ADM_TAG_DIALNORM_VALUE
    },
    {
        "copyRightB",
        DLB_ADM_ENTITY_TYPE_COPYRIGHTB,
        false,
        false,
        false,
        DLB_ADM_TAG_COPYRIGHTB_VALUE
    },
    {
        "origBs",
        DLB_ADM_ENTITY_TYPE_ORIGBS,
        false,
        false,
        false,
        DLB_ADM_TAG_ORIGBS_VALUE
    },
    {
        "langCode",
        DLB_ADM_ENTITY_TYPE_LANG_CODE,
        true,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    }, 
    {
        "langCod",
        DLB_ADM_ENTITY_TYPE_LANG_COD,
        false,
        false,
        false,
        DLB_ADM_TAG_LANG_COD_VALUE
    },
    {
        "audioProdInfo",
        DLB_ADM_ENTITY_TYPE_AUDIO_PROD_INFO,
        true,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "mixLevel",
        DLB_ADM_ENTITY_TYPE_MIXLEVEL,
        false,
        false,
        false,
        DLB_ADM_TAG_MIXLEVEL_VALUE
    },
    {
        "roomTyp",
        DLB_ADM_ENTITY_TYPE_ROOMTYP,
        false,
        false,
        false,
        DLB_ADM_TAG_ROOMTYP_VALUE
    },
{
        "extBsi1e",
        DLB_ADM_ENTITY_TYPE_EXTBSI1E,
        true,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "loRoCMixLev",
        DLB_ADM_ENTITY_TYPE_LORO_CMIXLEV,
        false,
        false,
        false,
        DLB_ADM_TAG_LORO_CMIXLEV_VALUE
    },
    {
        "loRoSurMixLev",
        DLB_ADM_ENTITY_TYPE_LORO_SURMIXLEV,
        false,
        false,
        false,
        DLB_ADM_TAG_LORO_SURMIXLEV_VALUE
    },     
    {
        "ltRtCMixLev",
        DLB_ADM_ENTITY_TYPE_LTRT_CMIXLEV,
        false,
        false,
        false,
        DLB_ADM_TAG_LTRT_CMIXLEV_VALUE
    },
    {
        "ltRtSurMixLev",
        DLB_ADM_ENTITY_TYPE_LTRT_SURMIXLEV,
        false,
        false,
        false,
        DLB_ADM_TAG_LTRT_SURMIXLEV_VALUE
    },     
    {
        "dMixMod",
        DLB_ADM_ENTITY_TYPE_DMIXMOD,
        false,
        false,
        false,
        DLB_ADM_TAG_DMIXMOD_VALUE
    },
    {
        "extBsi2e",
        DLB_ADM_ENTITY_TYPE_EXTBSI2E,
        true,
        false,
        false,
        DLB_ADM_TAG_UNKNOWN
    },
    {
        "dSurExMod",
        DLB_ADM_ENTITY_TYPE_DSUREXMOD,
        false,
        false,
        false,
        DLB_ADM_TAG_DSUREXMOD_VALUE
    },
    {
        "dHeadPhonMod",
        DLB_ADM_ENTITY_TYPE_DHEADPHONMOD,
        false,
        false,
        false,
        DLB_ADM_TAG_DHEADPHONMOD_VALUE
    },     
    {
        "adConvTyp",
        DLB_ADM_ENTITY_TYPE_ADCONVTYP,
        false,
        false,
        false,
        DLB_ADM_TAG_ADCONVTYP_VALUE
    },     
    {
        "compr1",
        DLB_ADM_ENTITY_TYPE_COMPR1,
        false,
        false,
        false,
        DLB_ADM_TAG_COMPR1_VALUE
    },
    {
        "dynRng1",
        DLB_ADM_ENTITY_TYPE_DYNRNG1,
        false,
        false,
        false,
        DLB_ADM_TAG_DYNRNG1_VALUE
    },
    {
        "programDescriptionText",
        DLB_ADM_ENTITY_TYPE_PROGRAM_DESCRIPTION_TEXT,
        false,
        false,
        false,
        DLB_ADM_TAG_PROGRAM_DESCRIPTION_TEXT_VALUE
    },                           
    {
        "encodeParameters",
        DLB_ADM_ENTITY_TYPE_ENCODE_PARAMETERS,
        true,
        false,
        false,
        DLB_ADM_TAG_ENCODE_PARAMETERS_ID
    },
    {
        "hpFOn",
        DLB_ADM_ENTITY_TYPE_HPFON,
        false,
        false,
        false,
        DLB_ADM_TAG_HPFON_VALUE
    },
    {
        "bwLpFOn",
        DLB_ADM_ENTITY_TYPE_BWLPFON,
        false,
        false,
        false,
        DLB_ADM_TAG_BWLPFON_VALUE
    },
    {
        "lfeLpFOn",
        DLB_ADM_ENTITY_TYPE_LFELPFON,
        false,
        false,
        false,
        DLB_ADM_TAG_LFELPFON_VALUE
    },
    {
        "sur90On",
        DLB_ADM_ENTITY_TYPE_SUR90ON,
        false,
        false,
        false,
        DLB_ADM_TAG_SUR90ON_VALUE
    },
    {
        "surAttOn",
        DLB_ADM_ENTITY_TYPE_SURRATTON,
        false,
        false,
        false,
        DLB_ADM_TAG_SURRATTON_VALUE
    },
    {
        "rfPremphOn",
        DLB_ADM_ENTITY_TYPE_RFPREMPHON,
        false,
        false,
        false,
        DLB_ADM_TAG_RFPREMPHON_VALUE
    }                                                      
    // ... component entities (no ADM identifier)
};
