/************************************************************************
 * dlb_pmd
 * Copyright (c) 2020 - 2022, Dolby Laboratories Inc.
 * Copyright (c) 2022, Dolby International AB.
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 **********************************************************************/

#ifndef DLB_PMD_TEST_DATA_H
#define DLB_PMD_TEST_DATA_H

#include "dlb_pmd/include/dlb_pmd_types.h"

static const char *smallXML1 GTEST_ATTRIBUTE_UNUSED_ =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<frame version=\"ITU-R_BS.2125-1\">\n"
"  <frameHeader>\n"
"    <frameFormat frameFormatID=\"FF_00000000001\" type=\"full\" start=\"00:00:00.00000\" duration=\"00:00:00.02000\">\n"
"    </frameFormat>\n"
"    <transportTrackFormat transportID=\"TP_0001\" transportName=\"X\" numIDs=\"2\" numTracks=\"2\">\n"
"      <audioTrack trackID=\"1\">\n"
"        <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"2\">\n"
"        <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"    </transportTrackFormat>\n"
"  </frameHeader>\n"
"  <audioFormatExtended version=\"ITU-R_BS.2076-3\">\n"
"    <audioProgramme audioProgrammeID=\"APR_1001\" audioProgrammeName=\"English\" audioProgrammeLanguage=\"eng\">\n"
"      <audioProgrammeLabel language=\"fr\">Francais</audioProgrammeLabel>\n"
"      <audioContentIDRef>ACO_1001</audioContentIDRef>\n"
"    </audioProgramme>\n"
"    <audioContent audioContentID=\"ACO_1001\" audioContentName=\"Stereo Main\">\n"
"      <audioObjectIDRef>AO_1001</audioObjectIDRef>\n"
"      <dialogue mixedContentKind=\"2\">2</dialogue>\n"
"    </audioContent>\n"
"    <audioObject audioObjectID=\"AO_1001\" audioObjectName=\"Stereo Main\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00011001\" audioPackFormatName=\"RoomCentric_2.0\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011001\" audioChannelFormatName=\"RoomCentricLeft\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011001_00000001\">\n"
"        <speakerLabel>RC_L</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011002\" audioChannelFormatName=\"RoomCentricRight\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011002_00000001\">\n"
"        <speakerLabel>RC_R</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioTrackUID UID=\"ATU_00000001\">\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000002\">\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"    </audioTrackUID>\n"
"  </audioFormatExtended>\n"
"</frame>\n"
;

static const char *smallXML2 GTEST_ATTRIBUTE_UNUSED_ =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<frame version=\"ITU-R_BS.2125-1\">\n"
"  <frameHeader>\n"
"    <frameFormat frameFormatID=\"FF_00000000001\" type=\"full\" start=\"00:00:00.00000\" duration=\"00:00:00.02000\">\n"
"    </frameFormat>\n"
"    <transportTrackFormat transportID=\"TP_0001\" transportName=\"PMD Audio Interface\" numIDs=\"2\" numTracks=\"2\">\n"
"      <audioTrack trackID=\"1\">\n"
"        <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"2\">\n"
"        <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"    </transportTrackFormat>\n"
"  </frameHeader>\n"
"  <audioFormatExtended version=\"ITU-R_BS.2076-3\">\n"
"    <audioProgramme audioProgrammeID=\"APR_1001\" audioProgrammeName=\"English\" audioProgrammeLanguage=\"eng\">\n"
"      <audioProgrammeLabel language=\"eng\">English</audioProgrammeLabel>\n"
"      <audioProgrammeLabel language=\"fr\">Francais</audioProgrammeLabel>\n"
"      <audioContentIDRef>ACO_1001</audioContentIDRef>\n"
"    </audioProgramme>\n"
"    <audioContent audioContentID=\"ACO_1001\" audioContentName=\"Stereo Main\">\n"
"      <dialogue mixedContentKind=\"2\">2</dialogue>\n"
"      <audioObjectIDRef>AO_1001</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioObject audioObjectID=\"AO_1001\" audioObjectName=\"Stereo Main\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00011001\" audioPackFormatName=\"RoomCentric_2.0\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011001\" audioChannelFormatName=\"RoomCentricLeft\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011001_00000001\">\n"
"        <speakerLabel>RC_L</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011002\" audioChannelFormatName=\"RoomCentricRight\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011002_00000001\">\n"
"        <speakerLabel>RC_R</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioTrackUID UID=\"ATU_00000001\">\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000002\">\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"  </audioFormatExtended>\n"
"</frame>\n"
;

static const char *stereo_2D_ADM GTEST_ATTRIBUTE_UNUSED_ =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<frame version=\"ITU-R_BS.2125-1\">\n"
"  <frameHeader>\n"
"    <frameFormat frameFormatID=\"FF_00000000001\" type=\"full\" start=\"00:00:00.00000\" duration=\"00:00:00.02000\" flowID=\"f8cc7821-09b2-41cb-bd42-ec35e9fcb9a8\">\n"
"    </frameFormat>\n"
"    <transportTrackFormat transportID=\"TP_0001\" transportName=\"X\" numIDs=\"4\" numTracks=\"4\">\n"
"      <audioTrack trackID=\"1\">\n"
"        <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"2\">\n"
"        <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"3\">\n"
"        <audioTrackUIDRef>ATU_00000003</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"4\">\n"
"        <audioTrackUIDRef>ATU_00000004</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"    </transportTrackFormat>\n"
"  </frameHeader>\n"
"  <audioFormatExtended version=\"ITU-R_BS.2076-3\">\n"
"    <audioProgramme audioProgrammeID=\"APR_1001\" audioProgrammeName=\"English\" audioProgrammeLanguage=\"en\">\n"
"      <audioProgrammeLabel language=\"fr\">Anglais</audioProgrammeLabel>\n"
"      <audioContentIDRef>ACO_1001</audioContentIDRef>\n"
"      <audioContentIDRef>ACO_1002</audioContentIDRef>\n"
"    </audioProgramme>\n"
"    <audioProgramme audioProgrammeID=\"APR_1002\" audioProgrammeName=\"Francais\" audioProgrammeLanguage=\"fr\">\n"
"      <audioProgrammeLabel language=\"en\">French</audioProgrammeLabel>\n"
"      <audioContentIDRef>ACO_1001</audioContentIDRef>\n"
"      <audioContentIDRef>ACO_1003</audioContentIDRef>\n"
"    </audioProgramme>\n"
"    <audioContent audioContentID=\"ACO_1001\" audioContentName=\"Stereo M+E\">\n"
"      <dialogue mixedContentKind=\"2\">2</dialogue>\n"
"      <audioObjectIDRef>AO_1001</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioContent audioContentID=\"ACO_1002\" audioContentName=\"English Dialog\">\n"
"      <dialogue dialogueContentKind=\"1\">1</dialogue>\n"
"      <audioObjectIDRef>AO_1002</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioContent audioContentID=\"ACO_1003\" audioContentName=\"French Dialog\">\n"
"      <dialogue dialogueContentKind=\"1\">1</dialogue>\n"
"      <audioObjectIDRef>AO_1003</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioObject audioObjectID=\"AO_1001\" audioObjectName=\"Stereo M+E\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioObject audioObjectID=\"AO_1002\" audioObjectName=\"English Dialog\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00011002</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000003</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioObject audioObjectID=\"AO_1003\" audioObjectName=\"French Dialog\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00031001</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000004</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00011001\" audioPackFormatName=\"RoomCentric_2.0\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00011002\" audioPackFormatName=\"RoomCentric_Center\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioChannelFormatIDRef>AC_00011003</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00031001\" audioPackFormatName=\"Dialog Object\" typeLabel=\"0003\" typeDefinition=\"Objects\">\n"
"      <audioChannelFormatIDRef>AC_00031001</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011001\" audioChannelFormatName=\"RoomCentricLeft\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011001_00000001\">\n"
"        <speakerLabel>RC_L</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011002\" audioChannelFormatName=\"RoomCentricRight\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011002_00000001\">\n"
"        <speakerLabel>RC_R</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011003\" audioChannelFormatName=\"RoomCentricCenter\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011003_00000001\">\n"
"        <speakerLabel>RC_C</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">0.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00031001\" audioChannelFormatName=\"Dialog Object\" typeLabel=\"0003\" typeDefinition=\"Objects\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00031001_00000001\">\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">0.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioTrackUID UID=\"ATU_00000001\">\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000002\">\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000003\">\n"
"      <audioPackFormatIDRef>AP_00011002</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011003</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000004\">\n"
"      <audioPackFormatIDRef>AP_00031001</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00031001</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"  </audioFormatExtended>\n"
"</frame>\n"
;

static const char *stereo_2D_PMD GTEST_ATTRIBUTE_UNUSED_ =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<Smpte2109>\n"
"    <ContainerConfig>\n"
"        <SampleOffset>0</SampleOffset>\n"
"        <DynamicTags>\n"
"        </DynamicTags>\n"
"    </ContainerConfig>\n"
"    <ProfessionalMetadata version=\"11.0\">\n"
"        <Title>Small Stereo Program</Title>\n"
"        <AudioSignals>\n"
"            <AudioSignal id=\"1\">\n"
"                <Name>Signal 1</Name>\n"
"            </AudioSignal>\n"
"            <AudioSignal id=\"2\">\n"
"                <Name>Signal 2</Name>\n"
"            </AudioSignal>\n"
"            <AudioSignal id=\"3\">\n"
"                <Name>Signal 3</Name>\n"
"            </AudioSignal>\n"
"            <AudioSignal id=\"4\">\n"
"                <Name>Signal 4</Name>\n"
"            </AudioSignal>\n"
"        </AudioSignals>\n"
"        <AudioElements>\n"
"            <AudioBed id=\"1\">\n"
"                <Name>Stereo M+E</Name>\n"
"                <SpeakerConfig>2.0</SpeakerConfig>\n"
"                <OutputTargets>\n"
"                    <OutputTarget id=\"Left\">\n"
"                        <AudioSignals>\n"
"                            <ID>1</ID>\n"
"                        </AudioSignals>\n"
"                    </OutputTarget>\n"
"                    <OutputTarget id=\"Right\">\n"
"                        <AudioSignals>\n"
"                            <ID>2</ID>\n"
"                        </AudioSignals>\n"
"                    </OutputTarget>\n"
"                </OutputTargets>\n"
"            </AudioBed>\n"
"            <AudioObject id=\"2\">\n"
"                <Name>English Dialog</Name>\n"
"                <Class>Dialog</Class>\n"
"                <DynamicUpdates>False</DynamicUpdates>\n"
"                <X_Pos>0.00</X_Pos>\n"
"                <Y_Pos>1.00</Y_Pos>\n"
"                <Z_Pos>0.00</Z_Pos>\n"
"                <Size>0.00</Size>\n"
"                <Size_3D>False</Size_3D>\n"
"                <Diverge>False</Diverge>\n"
"                <AudioSignal>3</AudioSignal>\n"
"                <SourceGainDB>0.0dB</SourceGainDB>\n"
"            </AudioObject>\n"
"            <AudioObject id=\"3\">\n"
"                <Name>French Dialog</Name>\n"
"                <Class>Dialog</Class>\n"
"                <DynamicUpdates>False</DynamicUpdates>\n"
"                <X_Pos>0.00</X_Pos>\n"
"                <Y_Pos>1.00</Y_Pos>\n"
"                <Z_Pos>0.00</Z_Pos>\n"
"                <Size>0.00</Size>\n"
"                <Size_3D>False</Size_3D>\n"
"                <Diverge>False</Diverge>\n"
"                <AudioSignal>4</AudioSignal>\n"
"                <SourceGainDB>0.0dB</SourceGainDB>\n"
"            </AudioObject>\n"
"        </AudioElements>\n"
"        <Presentations>\n"
"            <Presentation id=\"1\">\n"
"                <Name language=\"en\">English</Name>\n"
"                <Name language=\"fr\">Anglais</Name>\n"
"                <Config>2.0 ME + D</Config>\n"
"                <Language>en</Language>\n"
"                <Element>1</Element>\n"
"                <Element>2</Element>\n"
"            </Presentation>\n"
"            <Presentation id=\"2\">\n"
"                <Name language=\"fr\">Francais</Name>\n"
"                <Name language=\"en\">French</Name>\n"
"                <Config>2.0 ME + D</Config>\n"
"                <Language>fr</Language>\n"
"                <Element>1</Element>\n"
"                <Element>3</Element>\n"
"            </Presentation>\n"
"        </Presentations>\n"
"        <EncoderConfigurations>\n"
"        </EncoderConfigurations>\n"
"        <IAT>\n"
"            <Content_ID><UUID>f8cc7821-09b2-41cb-bd42-ec35e9fcb9a8</UUID></Content_ID>\n"
"            <Timestamp>0</Timestamp>\n"
"        </IAT>\n"
"    </ProfessionalMetadata>\n"
"</Smpte2109>\n"
;

static const char *extraObjectPMD GTEST_ATTRIBUTE_UNUSED_ =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<Smpte2109>\n"
"    <ContainerConfig>\n"
"        <SampleOffset>0</SampleOffset>\n"
"        <DynamicTags>\n"
"        </DynamicTags>\n"
"    </ContainerConfig>\n"
"    <ProfessionalMetadata version=\"11.0\">\n"
"        <Title>file \"extra_ob.sadm.xml\" converted from S-ADM</Title>\n"
"        <AudioSignals>\n"
"            <AudioSignal id=\"1\">\n"
"                <Name>Signal 1</Name>\n"
"            </AudioSignal>\n"
"            <AudioSignal id=\"2\">\n"
"                <Name>Signal 2</Name>\n"
"            </AudioSignal>\n"
"            <AudioSignal id=\"3\">\n"
"                <Name>Signal 3</Name>\n"
"            </AudioSignal>\n"
"            <AudioSignal id=\"4\">\n"
"                <Name>Signal 4</Name>\n"
"            </AudioSignal>\n"
"        </AudioSignals>\n"
"        <AudioElements>\n"
"            <AudioBed id=\"1\">\n"
"                <Name>Stereo M+E</Name>\n"
"                <SpeakerConfig>2.0</SpeakerConfig>\n"
"                <OutputTargets>\n"
"                    <OutputTarget id=\"Left\">\n"
"                        <AudioSignals>\n"
"                            <ID>1</ID>\n"
"                        </AudioSignals>\n"
"                    </OutputTarget>\n"
"                    <OutputTarget id=\"Right\">\n"
"                        <AudioSignals>\n"
"                            <ID>2</ID>\n"
"                        </AudioSignals>\n"
"                    </OutputTarget>\n"
"                </OutputTargets>\n"
"            </AudioBed>\n"
"            <AudioObject id=\"2\">\n"
"                <Name>English Dialog</Name>\n"
"                <Class>Dialog</Class>\n"
"                <DynamicUpdates>False</DynamicUpdates>\n"
"                <X_Pos>0.00</X_Pos>\n"
"                <Y_Pos>1.00</Y_Pos>\n"
"                <Z_Pos>0.00</Z_Pos>\n"
"                <Size>0.00</Size>\n"
"                <Size_3D>False</Size_3D>\n"
"                <Diverge>False</Diverge>\n"
"                <AudioSignal>3</AudioSignal>\n"
"                <SourceGainDB>0.0dB</SourceGainDB>\n"
"            </AudioObject>\n"
"            <AudioObject id=\"3\">\n"
"                <Name>Emergency Alert</Name>\n"
"                <Class>Emergency Alert</Class>\n"
"                <DynamicUpdates>False</DynamicUpdates>\n"
"                <X_Pos>0.00</X_Pos>\n"
"                <Y_Pos>1.00</Y_Pos>\n"
"                <Z_Pos>0.00</Z_Pos>\n"
"                <Size>0.00</Size>\n"
"                <Size_3D>False</Size_3D>\n"
"                <Diverge>False</Diverge>\n"
"                <AudioSignal>4</AudioSignal>\n"
"                <SourceGainDB>0.0dB</SourceGainDB>\n"
"            </AudioObject>\n"
"        </AudioElements>\n"
"        <Presentations>\n"
"            <Presentation id=\"1\">\n"
"                <Name language=\"en\">English</Name>\n"
"                <Config>2.0 ME + D</Config>\n"
"                <Language>en</Language>\n"
"                <Element>1</Element>\n"
"                <Element>2</Element>\n"
"            </Presentation>\n"
"        </Presentations>\n"
"        <EncoderConfigurations>\n"
"        </EncoderConfigurations>\n"
"        <IAT>\n"
"            <Content_ID><UUID>f8cc7821-09b2-41cb-bd42-ec35e9fcb9a8</UUID></Content_ID>\n"
"            <Timestamp>0</Timestamp>\n"
"        </IAT>\n"
"    </ProfessionalMetadata>\n"
"</Smpte2109>\n"
;

static const char *extraObjectADMEmission GTEST_ATTRIBUTE_UNUSED_ =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<frame version=\"ITU-R_BS.2125-1\">\n"
"  <frameHeader>\n"
"    <frameFormat frameFormatID=\"FF_00000000001\" type=\"full\" start=\"00:00:00.00000\" duration=\"00:00:00.02000\" flowID=\"f8cc7821-09b2-41cb-bd42-ec35e9fcb9a8\">\n"
"    </frameFormat>\n"
"    <transportTrackFormat transportID=\"TP_0001\" transportName=\"PMD Audio Interface\" numIDs=\"4\" numTracks=\"4\">\n"
"      <audioTrack trackID=\"1\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"2\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"3\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_00000003</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"4\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_00000004</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"    </transportTrackFormat>\n"
"    <profileList>\n"
"      <profile profileName=\"AdvSS Emission S-ADM Profile\" profileVersion=\"1.0.0\" profileLevel=\"1\">ITU-R BS.[ADM-NGA-EMISSION]-X</profile>\n"
"    </profileList>\n"
"  </frameHeader>\n"
"  <audioFormatExtended version=\"ITU-R_BS.2076-3\">\n"
"    <audioProgramme audioProgrammeID=\"APR_1001\" audioProgrammeName=\"English\" audioProgrammeLanguage=\"en\">\n"
"      <audioProgrammeLabel language=\"en\">English</audioProgrammeLabel>\n"
"      <loudnessMetadata>\n"
"        <integratedLoudness>-23.00</integratedLoudness>\n"
"      </loudnessMetadata>\n"
"      <audioContentIDRef>ACO_1001</audioContentIDRef>\n"
"      <audioContentIDRef>ACO_1002</audioContentIDRef>\n"
"    </audioProgramme>\n"
"    <audioContent audioContentID=\"ACO_1001\" audioContentName=\"Stereo M+E\" audioContentLanguage=\"en\">\n"
"      <dialogue mixedContentKind=\"2\">2</dialogue>\n"
"      <loudnessMetadata>\n"
"        <integratedLoudness>-23.00</integratedLoudness>\n"
"      </loudnessMetadata>\n"
"      <audioObjectIDRef>AO_1001</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioContent audioContentID=\"ACO_1002\" audioContentName=\"English Dialog\" audioContentLanguage=\"en\">\n"
"      <dialogue dialogueContentKind=\"1\">1</dialogue>\n"
"      <loudnessMetadata>\n"
"        <dialogueLoudness>-23.00</dialogueLoudness>\n"
"      </loudnessMetadata>\n"
"      <audioObjectIDRef>AO_1002</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioContent audioContentID=\"ACO_1003\" audioContentName=\"Emergency Alert\">\n"
"      <dialogue dialogueContentKind=\"6\">1</dialogue>\n"
"      <loudnessMetadata>\n"
"        <integratedLoudness>-23.00</integratedLoudness>\n"
"      </loudnessMetadata>\n"
"      <audioObjectIDRef>AO_1003</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioObject audioObjectID=\"AO_1001\" audioObjectName=\"Stereo M+E\" interact=\"0\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioObject audioObjectID=\"AO_1002\" audioObjectName=\"English Dialog\" interact=\"0\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00031002</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000003</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioObject audioObjectID=\"AO_1003\" audioObjectName=\"Emergency Alert\" interact=\"0\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00031003</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000004</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00011001\" audioPackFormatName=\"RoomCentric_2.0\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00031002\" audioPackFormatName=\"English Dialog\" typeLabel=\"0003\" typeDefinition=\"Objects\">\n"
"      <audioChannelFormatIDRef>AC_00031002</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00031003\" audioPackFormatName=\"Emergency Alert\" typeLabel=\"0003\" typeDefinition=\"Objects\">\n"
"      <audioChannelFormatIDRef>AC_00031003</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011001\" audioChannelFormatName=\"RoomCentricLeft\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011001_00000001\">\n"
"        <speakerLabel>RC_L</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011002\" audioChannelFormatName=\"RoomCentricRight\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011002_00000001\">\n"
"        <speakerLabel>RC_R</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00031002\" audioChannelFormatName=\"English Dialog\" typeLabel=\"0003\" typeDefinition=\"Objects\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00031002_00000001\">\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">0.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00031003\" audioChannelFormatName=\"Emergency Alert\" typeLabel=\"0003\" typeDefinition=\"Objects\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00031003_00000001\">\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">0.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioTrackUID UID=\"ATU_00000001\">\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000002\">\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000003\">\n"
"      <audioPackFormatIDRef>AP_00031002</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00031002</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000004\">\n"
"      <audioPackFormatIDRef>AP_00031003</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00031003</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <profileList>\n"
"      <profile profileName=\"AdvSS Emission S-ADM Profile\" profileVersion=\"1.0.0\" profileLevel=\"1\">ITU-R BS.[ADM-NGA-EMISSION]-X</profile>\n"
"    </profileList>\n"
"  </audioFormatExtended>\n"
"</frame>\n"
;

static const char *extraObjectADM GTEST_ATTRIBUTE_UNUSED_ =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<frame version=\"ITU-R_BS.2125-1\">\n"
"  <frameHeader>\n"
"    <frameFormat frameFormatID=\"FF_00000000001\" type=\"full\" start=\"00:00:00.00000\" duration=\"00:00:00.02000\" flowID=\"f8cc7821-09b2-41cb-bd42-ec35e9fcb9a8\">\n"
"    </frameFormat>\n"
"    <transportTrackFormat transportID=\"TP_0001\" transportName=\"PMD Audio Interface\" numIDs=\"4\" numTracks=\"4\">\n"
"      <audioTrack trackID=\"1\">\n"
"        <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"2\">\n"
"        <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"3\">\n"
"        <audioTrackUIDRef>ATU_00000003</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"4\">\n"
"        <audioTrackUIDRef>ATU_00000004</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"    </transportTrackFormat>\n"
"  </frameHeader>\n"
"  <audioFormatExtended version=\"ITU-R_BS.2076-3\">\n"
"    <audioProgramme audioProgrammeID=\"APR_1001\" audioProgrammeName=\"English\" audioProgrammeLanguage=\"en\">\n"
"      <audioProgrammeLabel language=\"en\">English</audioProgrammeLabel>\n"
"      <audioContentIDRef>ACO_1001</audioContentIDRef>\n"
"      <audioContentIDRef>ACO_1002</audioContentIDRef>\n"
"    </audioProgramme>\n"
"    <audioContent audioContentID=\"ACO_1001\" audioContentName=\"Stereo M+E\">\n"
"      <dialogue mixedContentKind=\"2\">2</dialogue>\n"
"      <audioObjectIDRef>AO_1001</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioContent audioContentID=\"ACO_1002\" audioContentName=\"English Dialog\">\n"
"      <dialogue dialogueContentKind=\"1\">1</dialogue>\n"
"      <audioObjectIDRef>AO_1002</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioContent audioContentID=\"ACO_1003\" audioContentName=\"Emergency Alert\">\n"
"      <dialogue dialogueContentKind=\"6\">1</dialogue>\n"
"      <audioObjectIDRef>AO_1003</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioObject audioObjectID=\"AO_1001\" audioObjectName=\"Stereo M+E\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioObject audioObjectID=\"AO_1002\" audioObjectName=\"English Dialog\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00031002</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000003</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioObject audioObjectID=\"AO_1003\" audioObjectName=\"Emergency Alert\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00031003</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000004</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00011001\" audioPackFormatName=\"RoomCentric_2.0\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00031002\" audioPackFormatName=\"English Dialog\" typeLabel=\"0003\" typeDefinition=\"Objects\">\n"
"      <audioChannelFormatIDRef>AC_00031002</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00031003\" audioPackFormatName=\"Emergency Alert\" typeLabel=\"0003\" typeDefinition=\"Objects\">\n"
"      <audioChannelFormatIDRef>AC_00031003</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011001\" audioChannelFormatName=\"RoomCentricLeft\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011001_00000001\">\n"
"        <speakerLabel>RC_L</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011002\" audioChannelFormatName=\"RoomCentricRight\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011002_00000001\">\n"
"        <speakerLabel>RC_R</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00031002\" audioChannelFormatName=\"English Dialog\" typeLabel=\"0003\" typeDefinition=\"Objects\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00031002_00000001\">\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">0.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00031003\" audioChannelFormatName=\"Emergency Alert\" typeLabel=\"0003\" typeDefinition=\"Objects\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00031003_00000001\">\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">0.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioTrackUID UID=\"ATU_00000001\">\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000002\">\n"
"      <audioPackFormatIDRef>AP_00011001</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000003\">\n"
"      <audioPackFormatIDRef>AP_00031002</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00031002</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000004\">\n"
"      <audioPackFormatIDRef>AP_00031003</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00031003</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"  </audioFormatExtended>\n"
"</frame>\n"
;

#if !DLB_PMD_USE_ALT_SPKRS
static const char *altSpkrADM GTEST_ATTRIBUTE_UNUSED_ =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<frame>\n"
"  <frameHeader>\n"
"    <frameFormat frameFormatID=\"FF_00000000001\" type=\"full\" start=\"00:00:00.00000\" duration=\"00:00:00.02000\">\n"
"    </frameFormat>\n"
"    <transportTrackFormat transportID=\"TP_0001\" transportName=\"PMD Audio Interface\" numIDs=\"18\" numTracks=\"18\">\n"
"      <audioTrack trackID=\"1\">\n"
"        <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"2\">\n"
"        <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"3\">\n"
"        <audioTrackUIDRef>ATU_00000003</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"4\">\n"
"        <audioTrackUIDRef>ATU_00000004</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"5\">\n"
"        <audioTrackUIDRef>ATU_00000005</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"6\">\n"
"        <audioTrackUIDRef>ATU_00000006</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"7\">\n"
"        <audioTrackUIDRef>ATU_00000007</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"8\">\n"
"        <audioTrackUIDRef>ATU_00000008</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"9\">\n"
"        <audioTrackUIDRef>ATU_00000009</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"10\">\n"
"        <audioTrackUIDRef>ATU_0000000A</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"11\">\n"
"        <audioTrackUIDRef>ATU_0000000B</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"12\">\n"
"        <audioTrackUIDRef>ATU_0000000C</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"13\">\n"
"        <audioTrackUIDRef>ATU_0000000D</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"14\">\n"
"        <audioTrackUIDRef>ATU_0000000E</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"15\">\n"
"        <audioTrackUIDRef>ATU_0000000F</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"16\">\n"
"        <audioTrackUIDRef>ATU_00000010</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"17\">\n"
"        <audioTrackUIDRef>ATU_00000011</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"18\">\n"
"        <audioTrackUIDRef>ATU_00000012</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"    </transportTrackFormat>\n"
"  </frameHeader>\n"
"  <audioFormatExtended version=\"ITU-R_BS.2076-2\">\n"
"    <audioProgramme audioProgrammeID=\"APR_1001\" audioProgrammeName=\"Pres 1\" audioProgrammeLanguage=\"en\">\n"
"      <audioProgrammeLabel language=\"en\">Pres 1</audioProgrammeLabel>\n"
"      <audioContentIDRef>ACO_1001</audioContentIDRef>\n"
"    </audioProgramme>\n"
"    <audioProgramme audioProgrammeID=\"APR_1002\" audioProgrammeName=\"Pres 2\" audioProgrammeLanguage=\"en\">\n"
"      <audioProgrammeLabel language=\"en\">Pres 2</audioProgrammeLabel>\n"
"      <audioContentIDRef>ACO_1002</audioContentIDRef>\n"
"    </audioProgramme>\n"
"    <audioContent audioContentID=\"ACO_1001\" audioContentName=\"Bed 1\">\n"
"      <dialogue mixedContentKind=\"2\">2</dialogue>\n"
"      <audioObjectIDRef>AO_1001</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioContent audioContentID=\"ACO_1002\" audioContentName=\"Bed 2\">\n"
"      <dialogue mixedContentKind=\"2\">2</dialogue>\n"
"      <audioObjectIDRef>AO_1002</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioObject audioObjectID=\"AO_1001\" audioObjectName=\"Bed 1\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00011003</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000003</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000004</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000005</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000006</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioObject audioObjectID=\"AO_1002\" audioObjectName=\"Bed 2\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000007</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000008</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000009</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_0000000A</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_0000000B</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_0000000C</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_0000000D</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_0000000E</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_0000000F</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000010</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000011</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000012</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00011003\" audioPackFormatName=\"RoomCentric_5.1\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011003</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011004</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011005</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011006</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00011006\" audioPackFormatName=\"RoomCentric_7.1.4\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011003</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011004</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011005</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011006</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011007</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011008</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011009</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_0001100A</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_0001100D</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_0001100E</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011001\" audioChannelFormatName=\"RoomCentricLeft\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011001_00000001\">\n"
"        <speakerLabel>RC_L</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011002\" audioChannelFormatName=\"RoomCentricRight\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011002_00000001\">\n"
"        <speakerLabel>RC_R</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011003\" audioChannelFormatName=\"RoomCentricCenter\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011003_00000001\">\n"
"        <speakerLabel>RC_C</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">0.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011004\" audioChannelFormatName=\"RoomCentricLFE\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011004_00000001\">\n"
"        <speakerLabel>RC_LFE</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">-1.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011005\" audioChannelFormatName=\"RoomCentricLeftSideSurround\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011005_00000001\">\n"
"        <speakerLabel>RC_Lss</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">0.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011006\" audioChannelFormatName=\"RoomCentricRightSideSurround\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011006_00000001\">\n"
"        <speakerLabel>RC_Rss</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">1.00</position>\n"
"        <position coordinate=\"Y\">0.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011007\" audioChannelFormatName=\"RoomCentricLeftRearSurround\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011007_00000001\">\n"
"        <speakerLabel>RC_Lrs</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">-1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011008\" audioChannelFormatName=\"RoomCentricRightRearSurround\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011008_00000001\">\n"
"        <speakerLabel>RC_Rrs</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">1.00</position>\n"
"        <position coordinate=\"Y\">-1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011009\" audioChannelFormatName=\"RoomCentricLeftTopFront\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011009_00000001\">\n"
"        <speakerLabel>RC_Ltf</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">1.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_0001100A\" audioChannelFormatName=\"RoomCentricRightTopFront\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_0001100A_00000001\">\n"
"        <speakerLabel>RC_Rtf</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">1.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_0001100D\" audioChannelFormatName=\"RoomCentricLeftTopRear\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_0001100D_00000001\">\n"
"        <speakerLabel>RC_Ltr</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">-1.00</position>\n"
"        <position coordinate=\"Z\">1.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_0001100E\" audioChannelFormatName=\"RoomCentricRightTopRear\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_0001100E_00000001\">\n"
"        <speakerLabel>RC_Rtr</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">1.00</position>\n"
"        <position coordinate=\"Y\">-1.00</position>\n"
"        <position coordinate=\"Z\">1.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioTrackUID UID=\"ATU_00000001\">\n"
"      <audioPackFormatIDRef>AP_00011003</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000002\">\n"
"      <audioPackFormatIDRef>AP_00011003</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000003\">\n"
"      <audioPackFormatIDRef>AP_00011003</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011003</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000004\">\n"
"      <audioPackFormatIDRef>AP_00011003</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011004</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000005\">\n"
"      <audioPackFormatIDRef>AP_00011003</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011005</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000006\">\n"
"      <audioPackFormatIDRef>AP_00011003</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011006</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000007\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000008\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000009\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011003</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_0000000A\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011004</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_0000000B\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011005</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_0000000C\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011006</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_0000000D\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011007</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_0000000E\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011008</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_0000000F\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011009</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000010\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_0001100A</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000011\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_0001100D</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000012\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_0001100E</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"  </audioFormatExtended>\n"
"</frame>\n"
;
#else
static const char *altSpkrADM GTEST_ATTRIBUTE_UNUSED_ =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<frame version=\"ITU-R_BS.2125-1\">\n"
"  <frameHeader>\n"
"    <frameFormat frameFormatID=\"FF_00000000001\" type=\"full\" start=\"00:00:00.00000\" duration=\"00:00:00.02000\">\n"
"    </frameFormat>\n"
"    <transportTrackFormat transportID=\"TP_0001\" transportName=\"PMD Audio Interface\" numIDs=\"18\" numTracks=\"18\">\n"
"      <audioTrack trackID=\"1\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"2\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"3\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_00000003</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"4\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_00000004</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"5\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_00000005</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"6\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_00000006</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"7\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_00000007</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"8\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_00000008</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"9\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_00000009</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"10\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_0000000A</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"11\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_0000000B</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"12\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_0000000C</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"13\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_0000000D</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"14\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_0000000E</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"15\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_0000000F</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"16\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_00000010</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"17\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_00000011</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"      <audioTrack trackID=\"18\" formatLabel=\"0001\" formatDefinition=\"PCM\">\n"
"        <audioTrackUIDRef>ATU_00000012</audioTrackUIDRef>\n"
"      </audioTrack>\n"
"    </transportTrackFormat>\n"
"    <profileList>\n"
"      <profile profileName=\"AdvSS Emission S-ADM Profile\" profileVersion=\"1.0.0\" profileLevel=\"1\">ITU-R BS.[ADM-NGA-EMISSION]-X</profile>\n"
"    </profileList>\n"
"  </frameHeader>\n"
"  <audioFormatExtended version=\"ITU-R_BS.2076-3\">\n"
"    <audioProgramme audioProgrammeID=\"APR_1001\" audioProgrammeName=\"Pres 1\" audioProgrammeLanguage=\"en\">\n"
"      <audioProgrammeLabel language=\"en\">Pres 1</audioProgrammeLabel>\n"
"      <loudnessMetadata>\n"
"        <integratedLoudness>-23.00</integratedLoudness>\n"
"      </loudnessMetadata>\n"
"      <audioContentIDRef>ACO_1001</audioContentIDRef>\n"
"    </audioProgramme>\n"
"    <audioProgramme audioProgrammeID=\"APR_1002\" audioProgrammeName=\"Pres 2\" audioProgrammeLanguage=\"en\">\n"
"      <audioProgrammeLabel language=\"en\">Pres 2</audioProgrammeLabel>\n"
"      <loudnessMetadata>\n"
"        <integratedLoudness>-23.00</integratedLoudness>\n"
"      </loudnessMetadata>\n"
"      <audioContentIDRef>ACO_1002</audioContentIDRef>\n"
"    </audioProgramme>\n"
"    <audioContent audioContentID=\"ACO_1001\" audioContentName=\"Bed 1\" audioContentLanguage=\"en\">\n"
"      <dialogue mixedContentKind=\"2\">2</dialogue>\n"
"      <loudnessMetadata>\n"
"        <integratedLoudness>-23.00</integratedLoudness>\n"
"      </loudnessMetadata>\n"
"      <audioObjectIDRef>AO_1001</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioContent audioContentID=\"ACO_1002\" audioContentName=\"Bed 2\" audioContentLanguage=\"en\">\n"
"      <dialogue mixedContentKind=\"2\">2</dialogue>\n"
"      <loudnessMetadata>\n"
"        <integratedLoudness>-23.00</integratedLoudness>\n"
"      </loudnessMetadata>\n"
"      <audioObjectIDRef>AO_1002</audioObjectIDRef>\n"
"    </audioContent>\n"
"    <audioObject audioObjectID=\"AO_1001\" audioObjectName=\"Bed 1\" interact=\"0\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00011003</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000003</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000004</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000005</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000006</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioObject audioObjectID=\"AO_1002\" audioObjectName=\"Bed 2\" interact=\"0\">\n"
"      <gain gainUnit=\"dB\">0.00</gain>\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioTrackUIDRef>ATU_00000007</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000008</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000009</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_0000000A</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_0000000B</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_0000000C</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_0000000D</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_0000000E</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_0000000F</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000010</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000011</audioTrackUIDRef>\n"
"      <audioTrackUIDRef>ATU_00000012</audioTrackUIDRef>\n"
"    </audioObject>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00011003\" audioPackFormatName=\"RoomCentric_5.1\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011003</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011004</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011041</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011042</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioPackFormat audioPackFormatID=\"AP_00011006\" audioPackFormatName=\"RoomCentric_7.1.4\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011003</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011004</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011005</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011006</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011007</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011008</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011009</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_0001100A</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_0001100D</audioChannelFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_0001100E</audioChannelFormatIDRef>\n"
"    </audioPackFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011001\" audioChannelFormatName=\"RoomCentricLeft\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011001_00000001\">\n"
"        <speakerLabel>RC_L</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011002\" audioChannelFormatName=\"RoomCentricRight\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011002_00000001\">\n"
"        <speakerLabel>RC_R</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011003\" audioChannelFormatName=\"RoomCentricCenter\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011003_00000001\">\n"
"        <speakerLabel>RC_C</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">0.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011004\" audioChannelFormatName=\"RoomCentricLFE\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011004_00000001\">\n"
"        <speakerLabel>RC_LFE</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">-1.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011005\" audioChannelFormatName=\"RoomCentricLeftSideSurround\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011005_00000001\">\n"
"        <speakerLabel>RC_Lss</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">0.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011006\" audioChannelFormatName=\"RoomCentricRightSideSurround\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011006_00000001\">\n"
"        <speakerLabel>RC_Rss</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">1.00</position>\n"
"        <position coordinate=\"Y\">0.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011007\" audioChannelFormatName=\"RoomCentricLeftRearSurround\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011007_00000001\">\n"
"        <speakerLabel>RC_Lrs</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">-1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011008\" audioChannelFormatName=\"RoomCentricRightRearSurround\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011008_00000001\">\n"
"        <speakerLabel>RC_Rrs</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">1.00</position>\n"
"        <position coordinate=\"Y\">-1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011009\" audioChannelFormatName=\"RoomCentricLeftTopFront\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011009_00000001\">\n"
"        <speakerLabel>RC_Ltf</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">1.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_0001100A\" audioChannelFormatName=\"RoomCentricRightTopFront\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_0001100A_00000001\">\n"
"        <speakerLabel>RC_Rtf</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">1.00</position>\n"
"        <position coordinate=\"Y\">1.00</position>\n"
"        <position coordinate=\"Z\">1.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_0001100D\" audioChannelFormatName=\"RoomCentricLeftTopRear\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_0001100D_00000001\">\n"
"        <speakerLabel>RC_Ltr</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">-1.00</position>\n"
"        <position coordinate=\"Z\">1.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_0001100E\" audioChannelFormatName=\"RoomCentricRightTopRear\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_0001100E_00000001\">\n"
"        <speakerLabel>RC_Rtr</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">1.00</position>\n"
"        <position coordinate=\"Y\">-1.00</position>\n"
"        <position coordinate=\"Z\">1.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011041\" audioChannelFormatName=\"RoomCentricLeftSurround\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011041_00000001\">\n"
"        <speakerLabel>RC_Ls</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">-1.00</position>\n"
"        <position coordinate=\"Y\">-1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioChannelFormat audioChannelFormatID=\"AC_00011042\" audioChannelFormatName=\"RoomCentricRightSurround\" typeLabel=\"0001\" typeDefinition=\"DirectSpeakers\">\n"
"      <audioBlockFormat audioBlockFormatID=\"AB_00011042_00000001\">\n"
"        <speakerLabel>RC_Rs</speakerLabel>\n"
"        <gain gainUnit=\"dB\">0.00</gain>\n"
"        <cartesian>1</cartesian>\n"
"        <position coordinate=\"X\">1.00</position>\n"
"        <position coordinate=\"Y\">-1.00</position>\n"
"        <position coordinate=\"Z\">0.00</position>\n"
"      </audioBlockFormat>\n"
"    </audioChannelFormat>\n"
"    <audioTrackUID UID=\"ATU_00000001\">\n"
"      <audioPackFormatIDRef>AP_00011003</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000002\">\n"
"      <audioPackFormatIDRef>AP_00011003</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000003\">\n"
"      <audioPackFormatIDRef>AP_00011003</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011003</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000004\">\n"
"      <audioPackFormatIDRef>AP_00011003</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011004</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000005\">\n"
"      <audioPackFormatIDRef>AP_00011003</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011041</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000006\">\n"
"      <audioPackFormatIDRef>AP_00011003</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011042</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000007\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011001</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000008\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011002</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000009\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011003</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_0000000A\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011004</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_0000000B\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011005</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_0000000C\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011006</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_0000000D\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011007</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_0000000E\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011008</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_0000000F\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_00011009</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000010\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_0001100A</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000011\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_0001100D</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <audioTrackUID UID=\"ATU_00000012\">\n"
"      <audioPackFormatIDRef>AP_00011006</audioPackFormatIDRef>\n"
"      <audioChannelFormatIDRef>AC_0001100E</audioChannelFormatIDRef>\n"
"    </audioTrackUID>\n"
"    <profileList>\n"
"      <profile profileName=\"AdvSS Emission S-ADM Profile\" profileVersion=\"1.0.0\" profileLevel=\"1\">ITU-R BS.[ADM-NGA-EMISSION]-X</profile>\n"
"    </profileList>\n"
"  </audioFormatExtended>\n"
"</frame>\n"
;
#endif

#endif
