/*
 * Derived from: sony/nmos-cpp (Apache-2.0)
 * Modifications: Removed custom num_put template specializations and nlohmann json integration.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright (c) 2019-2025, Dolby Laboratories Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "cpprest/json_visit.h"

namespace web
{
    namespace json
    {
        namespace experimental
        {
            // sample stylesheet for the HTML generated by html_visitor
            const char* html_stylesheet = R"-stylesheet-(
.json
{
  font-family: monospace
}
.json .number, .json .boolean, .json .null
{
  color: blue
}
.json .string
{
  color: brown
}
.json .object
{
  color: grey
}
.json .array
{
  color: grey
}
.json ul, .json ol
{
  list-style: none;
  border-left: 0.5px dotted rgba(0, 128, 0, 0.25);
}
.json ul:empty, .json ol:empty
{
  display: none
}
.json .name
{
  color: purple
}
/* folding support */
.json .elided
{
  display: none
}
.json .toggle::before
{
  position: relative;
  left: -0.25em;
  color: green;
  user-select: none;
  content: '\25bc'; /* '\25be' is smaller */
}
.json .open.toggle::before
{
  content: '\25ba'; /* '\25b8' is smaller */
}
/* remove toggle for browsers that don't support user-select */
_:-ms-lang(x), .json .toggle::before
{
  content: ''
}
_:-ms-lang(x), .json .open.toggle::before
{
  content: ''
}
/* optional gutter toggles */
.json
{
  position: relative
}
.json.gutter
{
  padding-left: 1.5em
}
.json.gutter .toggle::before
{
  position: absolute;
  left: 0;
}
)-stylesheet-";

            // sample script for the HTML generated by html_visitor
            const char* html_script = R"-script-(
window.onload = function() {
  var json = document.getElementsByClassName('json');
  for (var i = 0; i < json.length; ++i) {
    json[i].onclick = function(e) {
      if (!e.target.classList.contains('toggle')) return;
      var normal = e.target.parentElement.querySelector(':scope > .normal');
      var elided = e.target.parentElement.querySelector(':scope > .elided');

      // get state
      var open = getComputedStyle(normal).display == 'inline';

      // toggle state
      open ? e.target.classList.add('open') : e.target.classList.remove('open');
      normal.style.display = open ? 'none' : 'inline';
      elided.style.display = open ? 'inline' : 'none';
    }
  }
}
)-script-";
        }
    }
}
